### PR TITLE
fix bug: import javax.annotation.CheckReturnValue cannot be resolved

### PR DESCRIPTION
**Pull request by wolfgang-ch**
There are some CheckReturnValue errors which I could fix with this change

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!
The `providedCompile` scope is needed, as such dependencies should only be used when building the library, not using it.

**Comment by wolfgang-ch** [comment]
When I use `compile` instead of `providedCompile` then the errors to not disappear

Gradle is new for me, have you any hint for me to fix it with `providedCompile` ?

I already cleaned the project but this didn't help.

**Comment by wolfgang-ch** [comment]
After setting

	<classpathentry kind="lib" path="C:/E/java-resources/com.google.code/jsr305-3.0.1.jar"/>

in `.classpath` the errors with `providedCompile` disappeared

**Comment by devemux86** [comment]
Do you use VTM with the included Gradle 2.14.1 wrapper or with the Gradle version provided by the IDE?

**Comment by wolfgang-ch** [comment]
I'm using Gradle from the IDE which is also 2.14.1

gradle

**Comment by devemux86** [comment]
Android Studio is used mostly, but Gradle needs to work in other IDE too.

The `providedCompile` is a custom configuration to separate the runtime dependencies, which shouldn't be carried as transitive to the applications.

Does Eclipse have a problem parsing that?
Strange as script is pure Gradle working from command line too.
In that case please open an issue to not forget it.

**Comment by wolfgang-ch** [comment]
This is the procedure to get the errors in Eclipse 4.6.1 with Gradle 2.14.1 plugins:

* Clone VTM git
* Create Eclipse general project with the VTM folder as root
* Add a Gradle nature to this project -> this will automatically
  - Create all .settings .classpath and .project files for all folders which contain a build.gradle file
  - Download all dependencies
  - Rename the VTM root project to vtm-parent

When this has finished then the above error will occure

**Pull request closed without merging**
