### PR TITLE
extrusions: light source calculation with normals

### PR DESCRIPTION
**Pull request by Gustl22**
Now light source is movable via `mLightPos`.

### CODE REVIEW

**Comment by devemux86** [comment]
Considering that default extrusion rendering is nice to remain, what variables need to change to test the feature in action?

**Comment by devemux86** [comment]
Meaning play with the `ExtrusionRenderer.mLightPos` to see changes?
Also would be nice to document its values / limits for convenience.

**Comment by Gustl22** [comment]
> Meaning play with the `ExtrusionRenderer.mLightPos` to see changes?

Yes, you can set it to any values (x,y,z) you want except (0,0,0). Extrusions and meshes slightly had different values, so I found a compromise with `{0.3f, 0.3f, 1f}` pointing at south-east.

To be public usable we could add a setter/getter with description. My purpose was to connect it to a Sun calculator, in combination with shadow renderer.

**Comment by devemux86** [comment]
Thanks, merged via 48a5c36c3146c534d52b91158fc301bf96035c30.

**Pull request closed without merging**
