### PR TITLE
GeometryUtils: Fix reverse clockwise check

### PR DESCRIPTION
**Pull request by Gustl22**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, specially for the tests, they're absolutely needed for algorithm methods. :slightly_smiling_face:

**Comment by Gustl22** [comment]
Sorry, I come up with this again. 

As we figured out in #687 VTM has a left-hand-side coordinate system. So depending on perspective the methods are reversed. `isClockwise` -> `isCounterClockwise`.

**Comment by devemux86** [comment]
So what do you mean?

**Comment by devemux86** [comment]
So what do you mean, is the PR wrong and should be reverted?

**Comment by Gustl22** [comment]
Yes, only the implementation of `isClockwise` and `isTrisClockwise`.

**Pull request merged**
