### PR TITLE
Disable vtm-web

### PR DESCRIPTION
**Pull request by devemux86**
Maintainers are needed for `vtm-web`.

Needs update for new libGDX, no vector map source to test,
and it makes development difficult on other popular platforms.

### CODE REVIEW

**Comment by schedul-xor** [comment]
I checked the current status of `vtm-web`, found out that it needs to be updated step-by-step.

New vector map source
----
I personally host an opensciencemap v4 vector map source of my own. Because it's hosted for my own purpose, it only contains partial OSM data (actually, Japan). But by using the same code, it is possible to host other country's data too. How about hosting an alternate opensciencemap v4 tile server with Germany's data in it (For example $50~/mo from my budget)?

LibGDX 1.11.0 support
----
I checked out ae7c7b1 and changed the tile source URL to my personal vector map source, found out that even though LibGDX version was 1.9.10, `vtm-web` was already broken at this point.

So the first step is to make `vtm-web` work properly with LibGDX 1.9.10.

Supporting LibGDX 1.11.0 will come next.

**Comment by devemux86** [comment]
Maybe it's possible to use [vtm-mvt](https://github.com/mapsforge/vtm/tree/master/vtm-mvt) module and its map sources?
There is already a compatible [openmaptiles](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/vtm/openmaptiles.xml) theme.

However, GWT makes everything more difficult to maintain.

**Comment by schedul-xor** [comment]
Broken codes should be put back to where it was. Making vtm-web support mvt sources is an alternate challenge, so opensciencemap-v4 tile sources are needed anyway.

I agree that GWT is making it difficult, but i'm sure it's possible. I'll prepare a patch soon.

**Comment by devemux86** [comment]
@schedul-xor 
If there is a working WebGL demo, we can mention it again in the readme (see [here](https://github.com/mapsforge/vtm/pull/973/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)).

**Comment by schedul-xor** [comment]
There is a working WebGL demo ready, added to readme (#978)

**Pull request merged**
