### PR TITLE
Create centroid based on the complete (none clipped) way

### PR DESCRIPTION
**Pull request by marq24**
https://groups.google.com/forum/#!topic/mapsforge-dev/s53jzjG1LPY

this is an inital PR in order to summ up the discussion in the forum - I can understand if this will generate too heavy impact on the overall performance of the lib.

If this PR will be rejected its fine for me - if this is at least triggering a discussion for a more general solution that will also work vor vector based maps

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks for the work!

This seems similar to the code in forum, except using the new `centerPosition` instead of using the `labelPosition` field or it has some other advantage?

**Comment by marq24** [comment]
yes - it is more or less the same - the reason to introduce the additional field (and do not hijack the lablePosition) is to allow the LabelTileLoaderHook to run it's own center calc code for Lables... this will fix the mentioned issue with the lake names being rendered not correctly... 

I also added the POLY_SYMBOL Parameter to allow to turn off this additional calc if the symbols are disabled in general

**Comment by devemux86** [comment]
> the reason to introduce the additional field (and do not hijack the lablePosition) is to allow the LabelTileLoaderHook to run it's own center calc code for Lables

Isn't `labelPosition` filled only for buildings via tag-mapping and in other polygons is calculated automatically? So water polygons (in example) don't have it already.
If `centerPosition` is added extra in labels algorithm, it will be used anyway. Probably can use it only in symbols algorithm.

Also `centerPosition` location in code puts it out of [optimization checks](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/labeling/LabelTileLoaderHook.java#L142) at top of `if` statement where checks for visible area take place.

**Comment by marq24** [comment]
looks like it's not my day - I'll need to do more internal testings... before making a PR - sorry for the wasted time...

**Comment by devemux86** [comment]
Nothing is wasted, we just need a good solution and it usually comes with ideas and tests. :slightly_smiling_face: 

To summarize:
- Your code in forum looks working for symbols
- I'd put it behind a flag in `Parameters`, so it's optional for start
- Need to double check how it behaves with labels (or disable it there?)

**Comment by marq24** [comment]
... I do believe that I actually did that with the latest changes in the `LabelTileLoaderHook` ...

if `Parameters.POLY_LABEL=true` the `centerPosition` will be ignored - and instead a more complicated center will be calculated in `PolyLabel`... 

so only if `Parameters.POLY_LABEL=false` and `Parameters.POLY_SYMBOL=true` the new code would be active... since I do not see currently a way to separate the LABEL handing from the SYMBOL one...

and also the fact, that in the case of `Parameters.POLY_LABEL=true` the `LabelTileLoaderHook` will calculate the center of the poly based on the clipped way data makes me feel uncomfortable... [and also the mentioned fact, that performing (even the simple) center for each way (for each tile) is far from being optimal].

so what do you think about this alternative approach?
The `GeometryBuffer` itself occupies always at least the memory for the float[] with a size of min 2048 values... Currently at index[0] the number of points is stored (that will be then read from this float[] to calculate the centroid (but this is already clipped) - when we would now store additionally the "unclipped/original" way points again e.g. in the `MapDatabase.decodeWayNodes` method? - and then use in the `LabelTileLoaderHook` (and the `PolyLabel`) the `element.index[pointNextPos]` instead of simply the `element.index[0]` - would you think that is an option? [I have to admit that I have not fully understand yet, when and how normally the `pointNextPos` is used]

**Comment by devemux86** [comment]
> since I do not see currently a way to separate the LABEL handing from the SYMBOL one...

I mentioned it just above. If use only `labelPosition` (like in forum) would be difficult, but if use new `centerPosition`, them simply not add it in labels code path, only in symbols code path.

**Comment by devemux86** [comment]
Labels are different than symbols, we usually want labels to replicate (e.g. in large lakes) and not have a label in center, which when zoom in will be several screens away.

So the changes should modify only the symbols code path, that was the purpose from the start.

**Comment by devemux86** [comment]
_I disabled via f5815203c4c7b5f8c1adc515d2fabbea9ee9b6ed the Mapbox polylabel as default algorithm to avoid map performance problems.
If is needed users can use the `Parameters.POLY_LABEL` flag in their apps._

**Comment by devemux86** [comment]
You're leaving the feature?
It's an interesting idea if handled correctly and offered as option for now.
I could push the changes if you won't work on it anymore.

**Comment by marq24** [comment]
I just need to rebase... that's all - a new PR will come

**Pull request closed without merging**
