### PR TITLE
Fix: Projection and High-Precision Rendering in VTM Fixed for good

### PR DESCRIPTION
**Pull request by braandl**
Changing Floats to Double for better coordinate precision with mapsforge files. Also migrated the MapDatabaseReader for better readability.

### CODE REVIEW

**Comment by devemux86** [comment]
Could you rebase your branch on latest master and force push the changes?

**Comment by braandl** [comment]
Yes, no problem!

**Comment by devemux86** [comment]
Thanks!
Please check the project building as it fails. :slightly_smiling_face: 

BTW in the PR is there just the data types change or other improvements too?
It's preferable to have each feature / fix in its own PR for less code to check and faster merging.

**Comment by braandl** [comment]
Hm, darn. I will look into this a little later, sorry! I did not recheck after rebaseing the project. 
I did not really change anything else, just wrapped the reader for the mapsforge files so it's readability is improved. i can remove that from the commit if you wish. i will provide an update later.

**Comment by hjanetzek** [comment]
@braandl I think you could have achieved your goal to have full precision for Mapsforge files simply by using double (or int) for lat/lon before they get transformed to tile coordinates. In other cases the GeometryBuffer is used for tile coordinates for which float should be more than sufficient.

**Comment by devemux86** [comment]
I agree with @hjanetzek here, need to exhaust all cases first.
If there is a solution involving just minor changes in e.g. the input of algorithms, then we should prefer it and avoid changing the whole library's structure. :slightly_smiling_face:

**Comment by hjanetzek** [comment]
@braandl have you tried to just use double within MapFileSource? This should fix the precision issue. Keeping float where possible will be better for performance.

**Comment by devemux86** [comment]
>have you tried to just use double within MapFileSource?

@hjanetzek do you mean `MapDatabase`?

**Comment by hjanetzek** [comment]
yes, that's the one I meant. Basically coordinates should be projected to tile coordinates before adding them to the float GeometryBuffer/MapElement to not loose precision.

**Pull request closed without merging**
