### PR TITLE
update iOS SVGh (exclude x86 native's)

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

**Comment by Longri** [comment]
#531 ?

**Comment by jerzykiler** [comment]
Yes that's the same exception and reverting this change fixes it.

**Comment by Longri** [comment]
Fore an older Version of XCode?

> Okay, after I updated macOS High Sierra 10.13.4 and also Xcode 9.3, now it's runing well on the simulator.
> I think the main problem because I used the old macOS Sierra 10.12.X and Xcode 8.3.

**Comment by jerzykiler** [comment]
I use the newest version of Xcode 9.3 (9E145) and macOS High Sierra 10.13.4

**Comment by jerzykiler** [comment]
On the other hand, the command:

`../gradlew robovmInstall --stacktrace` was failing with this exception

Caused by: org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo /Users/_secret_/_secret_/clean_vtm/vtm-ios-example/build/robovm/VtmApp.framework/Frameworks/SVGgh.framework/SVGgh -remove x86_64 -output /Users/_secret_/_secret_/clean_vtm/vtm-ios-example/build/robovm/VtmApp.framework/Frameworks/SVGgh.framework/SVGgh.tmp' failed (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
        at org.robovm.compiler.util.Executor.exec(Executor.java:344)
        at org.robovm.compiler.util.ToolchainUtil.lipoRemoveArchs(ToolchainUtil.java:311)
        at org.robovm.compiler.target.AbstractTarget$2.processFile(AbstractTarget.java:365)
        at org.robovm.compiler.config.Resource.walk(Resource.java:447)
        at org.robovm.compiler.config.Resource.walk(Resource.java:454)
        at org.robovm.compiler.config.Resource.walk(Resource.java:415)
        at org.robovm.compiler.target.AbstractTarget.copyDynamicFrameworks(AbstractTarget.java:341)
        at org.robovm.compiler.target.AbstractTarget.doInstall(AbstractTarget.java:464)
        at org.robovm.compiler.target.framework.FrameworkTarget.doInstall(FrameworkTarget.java:180)
        at org.robovm.compiler.target.AbstractTarget.install(AbstractTarget.java:438)
        at org.robovm.compiler.AppCompiler.install(AppCompiler.java:811)
        at org.robovm.gradle.tasks.AbstractRoboVMBuildTask.invoke(AbstractRoboVMBuildTask.java:55)
        ... 42 more

but with this update (excluding x86) it passes fine

**Pull request merged**
