### PR TITLE
LWJGL3 libGDX backend (#258)

### PR DESCRIPTION
**Pull request by Gustl22**
See #258, #714 and [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/U_NqCpSuUhA).

`vtm-desktop-lwjgl` and `vtm-desktop-lwjgl3` couldn't coexist / loaded in one module e.g. `vtm-playground` as LWJGL/LWJGL3 use different versions of their interfaces with equivalent package name.

So may can test in different branch or open new test module with `lwjgl3`.

### CODE REVIEW

**Comment by devemux86** [comment]
That's unfortunate, as prefer to not duplicate the examples in branches or modules, instead keep maintenance simple.
For now seems anyone wanting to use / test other backends can do it locally. Until thorough testing is done and see if LWJGL3 has improved beyond repository simplistic samples.

**Comment by devemux86** [comment]
Since they cannot be used together, can revert the package of both backends back to original `org.oscim.gdx` and then just need to change the dependency in `vtm-playground` to test anyone.

**Comment by Gustl22** [comment]
Cannot say what's the best solution here, but that might be a good one.

**Comment by devemux86** [comment]
I'll do some tests during the merge and see how it works.

**Comment by Gustl22** [comment]
Package naming also depends on if planing other backends :sweat_smile:

**Comment by devemux86** [comment]
Thanks, merged via 5f1c3c318685365ab789640412304536574581d2.

**Pull request closed without merging**
