### PR TITLE
Internal render theme improvements

### PR DESCRIPTION
**Pull request by Gustl22**
- add symbols for areas with names
- differ tavern, shop, health, accommodation, education, entertainment and default (with different colors)
- unifications on theme structure (more or less all themes)

I used the colors of OSM theme. If it's too colorful, can simply replace the colors in text-styles.

Feel free to change code if it isn't proper.

### CODE REVIEW

**Comment by devemux86** [comment]
Seems very nice!

- Shouldn't also other poi categories have in their labels their symbol color?
e.g. bank labels are still blue.
- Osmarender and Tronrender theme appear with less labels (e.g. missing buildings)?
BTW Osmarender and Osmagray are supposed to have same structure, except grayscale colors.

**Comment by Gustl22** [comment]
Thanks for reviewing.

- I introduced new color for `entertainment`, cause I think food/taverns not have that much in common with museums, etc. Adapt some symbols, too.
- Fixed missing buildings, and adapt Osmagray and Osmarender

**Comment by devemux86** [comment]
Why need changing SVG symbols and what are their changes?
We use (#251) the "positive + white glow" variant of [SJJB SVG map icons](http://www.sjjb.co.uk/mapicons/).
Their original collection can be found in repository [here](https://github.com/mapsforge/vtm/tree/master/vtm-themes/icons/symbols).

**Comment by Gustl22** [comment]
> Why need changing SVG symbols and what are their changes?

In my opinion the brown `tavern` color (**#734a08**) is used in OSM for too many different sectors.
So I created `entertainment` color (**#b7650c**) which is used for all entertainment things (is the old POI color).
Most icons in tourism folder have changed fill color (simply search for **#b7650c**).

If the colors should match OSM page, I can revert this color again, but keep text option for `entertainment`.

**Comment by devemux86** [comment]
SJJB symbols should be kept in their original form for reference, being public release and used by developers in their own themes via the `vtm-themes` module.

If need to add / modify symbols then can include them in [symbols](https://github.com/mapsforge/vtm/tree/master/vtm-themes/resources/assets/symbols) folder root to not mix with original ones.
We keep there our custom symbols (like did with dot_blue_dark).

BTW when modify a SVG please keep the original formatting and change only the color values with an editor, so we can easily recognize the changes.

**Comment by Gustl22** [comment]
Reordered the symbols, did some fixes. And revert node specific keys to its section.

**Comment by Gustl22** [comment]
I'm ready now. Forgot to reformat the symbols :grin:

**Comment by devemux86** [comment]
Note: probably circles are not much usable now since have still open #268 and more #269 (depending circle implementation).

**Comment by Gustl22** [comment]
Ok, thanks! Comment them out.

**Comment by devemux86** [comment]
Thanks for all that work and maintain formatting in themes and svg!
Really appreciate it, since know how much work is theme maintenance.
Maps appear much better now, readable and aesthetically pleasing. :slightly_smiling_face: 

Squashed and merged via 8e35a178d2f26987a5d069700be3a70420f50b4f.

**Pull request closed without merging**
