### PR TITLE
Feature/doubleprecision clean

### PR DESCRIPTION
**Pull request by braandl**
This is the same fix, that should change floats to doubles for more rendering precision with mapsforge. This branch is updated to provide a clean(er) path.

### CODE REVIEW

**Comment by braandl** [comment]
As promised a working branch to merge with the current codebase, fixing the mapsforge precision bug for zoomlevel > 17

**Comment by devemux86** [comment]
What improvements should we see in rendering at zoom 18?
See @hjanetzek 's comment in old PR [here](https://github.com/mapsforge/vtm/pull/226#issuecomment-258841217).

Because I made quick test with the PR and still see the same artifacts with Mapsforge maps, like the road at tile grid lines:

artifacts

**Comment by braandl** [comment]
old

new

Here you can see a strong difference. The map is not perfect, but in the first screenshot you can see that points are not rendered at the correct location.

**Comment by devemux86** [comment]
In 1st screenshot there aren't any symbols at all. What are the zoom levels?
Do you use a Mapsforge with elements in tag-mapping from zoom 18?

**Comment by braandl** [comment]
it is not about the symbols, it is about the ways. they differ a lot.

**Comment by braandl** [comment]
the other screenshot is just older and had no symbols in it, and I am to lazy to build an old app version now, just to get symbols in there too

**Comment by devemux86** [comment]
I have not seen such behavior in map files.
Can you point how we can reproduce it with a map?

**Comment by braandl** [comment]
Load a Mapsforge Map-File and zoom in.

**Comment by hjanetzek** [comment]
@devemux86 the cut-off sides of roads is due to the clipping of geometries to the tile boundaries. I think it depends on the map writer `bbox-enlargement` option.

**Comment by devemux86** [comment]
Please read my above comment, we have not seen anything strange with default `new MapFileTileSource(0, 17)`, where map view's zoom goes of course beyond 17.
With `new MapFileTileSource(0, 18)` there are the known artifacts shown above and in https://github.com/opensciencemap/vtm/issues/122, nothing else so far.

If you want to post a screenshot with debug grid enabled to where exactly can check the issue.

**Comment by devemux86** [comment]
@hjanetzek thanks for the tip!
I see in our map writer [documentation](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md) that we have default `bbox-enlargement=20`.
We could debug what happens there (BTW in Mapsforge renderer that works fine).

**Comment by braandl** [comment]
old

new

**Comment by hjanetzek** [comment]
@devemux86 oh there is also clipping done in MapDatabase. With a hard-coded 'buffer-enlargement' of 16 https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java#L388

**Comment by devemux86** [comment]
@braandl Mapsforge maps do not have content in that area to check.
Can you post a sample map and the data / tag-mapping to create it for us to test?

**Comment by devemux86** [comment]
`MapDatabase` could use a review (e.g. #109, #231), taking into account also Mapsforge equivalent [MapFile](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java).
If there is precision problem specifically with Mapsforge tile source, the logical step is to focus first in its reader.

**Comment by braandl** [comment]
Yeah, I did that first until I discovered that there is a round-off problem...
I was not able to find differences within the mapdatabase.

**Comment by devemux86** [comment]
I merged the PR in [issue_230](https://github.com/mapsforge/vtm/tree/issue_230) branch for anyone wanting to check it.

My tests so far show that render artifacts, as mentioned in #231, still exist even with that precision change. So we need to check also elsewhere.

**Comment by devemux86** [comment]
Thanks for the PR!
Closing here as we must first exhaust all possibilities with Mapsforge code as mentioned above and with a test case for those large zoom levels.

**Pull request closed without merging**
