### PR TITLE
update RoboVm to version 2.3.8, depended on the update of LibGdx to version 1.9.10

### PR DESCRIPTION
**Pull request by Longri**
fix CgBitmapContext changes on RoboVm

### CODE REVIEW

**Comment by devemux86** [comment]
It fails to build.
There doesn't seem a 2.3.8 [release](https://github.com/MobiVM/robovm/releases) on [Maven](https://search.maven.org/search?q=g:com.mobidevelop.robovm%20AND%20a:robovm-gradle-plugin&core=gav)?

**Comment by Longri** [comment]
Oh, okay the cgbitmapcontext changes are in the snapshot! I don't use iOS module from vtm on my project! I use a copy with 2.3.8-SNAPSHOT! There fix a problem with creating a large CgBitmapContext

**Comment by devemux86** [comment]
Let's wait the official release and can update the dependencies then.

**Comment by Longri** [comment]
Ok, then I will open a issue for not working iOS module, then you can't forgot them!

**Pull request closed without merging**
