### PR TITLE
vtm-web: move slf4j gwt logger provider to app implementations

### PR DESCRIPTION
**Pull request by Gustl22**
vtm-web already uses [gwt slf4j](https://github.com/FinamTrade/slf4j-gwt) logger [here](https://github.com/mapsforge/vtm/blob/master/vtm-web/src/org/oscim/gdx/VtmWeb.gwt.xml#L6).

Usually there's no warning as dependecies are loaded in app modules, but better move dependency to web module where it belongs to.
Can trigger warning e.g. with `./gradlew :vtm-web:gwtSuperDev`:
```
Loading inherited module 'ru.finam.slf4jgwt.logging.gwt.Logging'
         [ERROR] Unable to find 'ru/finam/slf4jgwt/logging/gwt/Logging.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

### CODE REVIEW

**Comment by devemux86** [comment]
Normally libraries should not force any log provider.
So `vtm-web` could be improved instead?

From SLF4J [documentation](https://www.slf4j.org/codes.html):
_"Note that embedded components such as libraries or frameworks should not declare a dependency on any SLF4J providers but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J provider, it imposes that provider on the end-user, thus negating SLF4J's purpose."_

**Comment by Gustl22** [comment]
Sure ;D
Only for comprehension: I don't understand the use case of this option of [finamTrade](https://github.com/FinamTrade/slf4j-gwt#usage) : 
`<inherits name="ru.finam.slf4jgwt.api.API"/>`
If want to have access to api `org.slf4j:slf4j-api` provides already the interface?

My proposal is to move `<inherits name="ru.finam.slf4jgwt.logging.gwt.Logging" />` to web-js and web-app modul descriptor then (?)

**Comment by devemux86** [comment]
> If want to have access to api org.slf4j:slf4j-api provides already the interface?

Correctly and that's the idea of such log abstractions like the SLF4J.
Users select the provider in apps and libraries provide only the interface.

> My proposal is to move <inherits name="ru.finam.slf4jgwt.logging.gwt.Logging" /> to web-js and web-app modul descriptor then (?)

GWT occasionally can be a bit strange, but that could be the correct action.

**Comment by Gustl22** [comment]
Updated the PR, but couldn't test `vtm-web-js`, but should work as well.

**Comment by devemux86** [comment]
Thanks, merged via 608edc2d464e6a19d1ebad78bdf494475e3546c3.

**Pull request closed without merging**
