### PR TITLE
Demonstrating MarkerLayer with Labels

### PR DESCRIPTION
**Pull request by telemaxx**
vtm 0.10 do not have a native function to display title and description.
this little program demonstrating a simple work around.

### CODE REVIEW

**Comment by devemux86** [comment]
Nice, essentially is via customized bitmap, symbol + text.
(similar to [AtlasMultiTextureTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/AtlasMultiTextureTest.java))

Also what encoding is the file?
Android Studio complains for UTF-8 and doesn't show non latin characters.

**Comment by devemux86** [comment]
> vtm 0.10 do not have a native function to display title and description.

A global solution would be difficult to describe, as there are far too many custom options (font, size, style, color, background, shape, ...). Often it's easier letting developers handle all those customized in the apps.

**Comment by telemaxx** [comment]
> Also what encoding is the file?
> Android Studio complains for UTF-8 and doesn't show non latin characters.
Standard encoding.
grafik


Maybe because of line 76:
`pts.add(new MarkerItem("Siegess**ä**ule, hidden description", "this is a hidden Description without a #", new GeoPoint(52.514543, 13.350119)));`

**Comment by devemux86** [comment]
_A recommendation is to use the default UTF-8 everywhere, as there will be such cases with encoding incompatibilities._

**Comment by telemaxx** [comment]
i changed to utf-8 and set the color of the boxes to pink. looks better with the pink dots.

**Comment by telemaxx** [comment]
> (similar to [AtlasMultiTextureTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/AtlasMultiTextureTest.java))
looks really a bit like that example...

> A global solution would be difficult to describe, as there are far too many custom options (font, size, style, color, background, shape, ...). Often it's easier letting developers handle all those customized in the apps.
yes, that is true. A the beginning i thought its complicate to implement the labels. but it was quite easy.

**Comment by telemaxx** [comment]
#237

**Comment by ocsike** [comment]
Can you post a preview image from the generated marker?

**Comment by telemaxx** [comment]
MarkerLayerWithLabelsTest.java
grafik
Map is turned and tilted to show that the text is always readable.

inside a real app, mytourbook:
https://groups.google.com/d/msg/mapsforge-dev/LYC4oHzzfe8/QOb8jn-vFQAJ

**Comment by devemux86** [comment]
Sorry but cannot merge at this state.
Please post a new PR with the code being in proper encoding.
Right now cannot even rebase or squash the commits...

**Comment by telemaxx** [comment]
i will try...

**Pull request closed without merging**
