### PR TITLE
Sun: set progress with custom time

### PR DESCRIPTION
**Pull request by Gustl22**
To be able to set progress with custom time instead of more abstract progress.

### CODE REVIEW

**Comment by devemux86** [comment]
The Java8 comments in `updateProgress` need to be moved in the new method too.

For another PR, the shadow samples now could use the new `setProgress`, as users can modify it easier to test the feature?

**Comment by Gustl22** [comment]
> The Java8 comments in updateProgress need to be moved in the new method too.

This affects more the `DateTimeAdapter` to remove it again, when Gwt supports regular `DateTime`, too. May we should remove it anyway.

> For another PR, the shadow samples now could use the new setProgress, as users can modify it easier to test the feature?

Set progress via time is not meant to show shadows / day cycle. It's far easier to set it via progress. Or what kind of example do you want to show the users?

**Comment by devemux86** [comment]
> Or what kind of example do you want to show the users?

Current samples are a bit difficult to modify, e.g. to make shadows cycle slower.
The sample in #688 is more easier to understand, if can do something similar?

**Comment by Gustl22** [comment]
Ok I'll try after merge.

**Comment by devemux86** [comment]
Thanks, merged via 311cc19134ec6633631971fd52bbaf278cd9b178.

**Pull request closed without merging**
