### PR TITLE
fix libgdx compatibele to run tests from playground

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks for that, I hadn't the time to look after this.

BTW it's recommended to create local branches for the pull requests. Then you can easily **rebase** (not merge) them with latest master.

Also PR commits should be squashed, in order to avoid the clutter in repository and have only the finally changed files together. One way is described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).
That step involves a deeper `git` knowledge and force push at the end (I can do it eventually).

**Comment by Longri** [comment]
I have say it, that I must learn PR. That's was my first try.

**Comment by devemux86** [comment]
It's really no problem. :smile:

**Comment by devemux86** [comment]
Merged via d1fd03a52fa03fb0abdc31d2ba2ddcc6375da2ee.

Related to #13.

**Pull request closed without merging**
