### PR TITLE
vtm-ios: remove slf4j-simple dependency

### PR DESCRIPTION
**Pull request by Longri**
I wondering from where the Logger coms on my project

### CODE REVIEW

**Comment by devemux86** [comment]
The `slf4j-api` is the core and actually Gradle can get it from `vtm`, so could be removed here.

But the `slf4j-simple` is one of its [bindings](https://www.slf4j.org/manual.html#swapping) and shouldn't forced by library, but be selected by users in the applications.

**Comment by Longri** [comment]
> But the slf4j-simple is one of its bindings and shouldn't forced by library, but be selected by users in the applications.

Thats the point way I have replaced at vtm-ios Module

> The slf4j-api is the core and actually Gradle can get it from vtm, so could be removed here.

This should be so, but for me (IntelliJ 2016.3.4) that does not work!
The same problem I have synonymous with the vtm android-exemple modules. Here the module should get the dependency to the vtm module, which I however always have to adjust again and before I committ back again.

**Comment by devemux86** [comment]
> This should be so, but for me (IntelliJ 2016.3.4) that does not work!

You should really try fixing that, as that's not normal Gradle behavior.
All module dependencies are coming from their parents, how only few only fail?

**Comment by Longri** [comment]
That is a problem with intelliJ!
if I build with Gradle all is ok!

Only IntelliJ shows Error's!
image


But I can run from IntelliJ !

**Comment by devemux86** [comment]
Can you try with Android Studio?

Are you sure you have not disabled the `transitive` nature of dependencies anywhere in your Gradle profile locations?

**Comment by devemux86** [comment]
>That is a problem with intelliJ!
if I build with Gradle all is ok!

That seems like some configuration issue in Idea settings or need to reopen a fresh cloned repository.

**Comment by Longri** [comment]
> That seems like some configuration issue in Idea settings or need to reopen a fresh cloned repository.
I have do it without success!

> Can you try with Android Studio?
No never again! A try gives many problems with RoboVm!

> Are you sure you have not disabled the transitive nature of dependencies anywhere in your Gradle profile locations?

not shure but I can't remember! I have no "gradle.properties" file found on my system!

**Comment by devemux86** [comment]
If you don't mind we better not overload modules with parent dependencies, because an IDE does not work correctly.
I would start with a new Idea profile, a fresh repository clone and deleted Gradle cache to test why this does not work.

So I'll just remove the `slf4j-simple` here?

**Comment by Longri** [comment]
I can not get it, but if you want, you can delete the slf4j-api from vtm-ios.
For me, it was mainly no slf4j-simple in vtm-ios to have.
I can live with it

**Comment by devemux86** [comment]
Merged via dc340a382e992fd4f80cbd0b43229c0cae88cfbf (removing `slf4j-simple`).

**Pull request closed without merging**
