### PR TITLE
Viewport toScreenPoint/fromScreenPoint consistency, fixes #28

### PR DESCRIPTION
**Pull request by andreynovikov**
This fixed problem in my application. Also have tested it on all screen corners for consistent to/from and from/to results.

### CODE REVIEW

**Comment by devemux86** [comment]
You mean #81?

**Comment by andreynovikov** [comment]
Yes, do not know how 28 came in...

**Comment by devemux86** [comment]
Hmm that may work for piped `toScreenPoint` / `fromScreenPoint` calls.
But it breaks the direct `fromScreenPoint` returning `GeoPoint` in wrong coordinates.

**Comment by devemux86** [comment]
For example `Viewport.fromScreenPoint(double x, double y, Point out)` is used in `vtm-app`'s `LocationOverlay`.

That worked, now the location never appears where it should, it's always in wrong position.

**Comment by andreynovikov** [comment]
Exactly! That's what I was talking about in #81 
`toScreenPoint` treats 0,0 as a screen center, and you [have to add half-screen-size](https://github.com/mapsforge/vtm/blob/master/vtm-app/src/org/oscim/app/location/LocationOverlay.java#L168). But `fromScreenPoint` treated 0,0 as a top-left corner. That's what I fixed. But I overlooked this part of code. It should be fixed. Should I?

**Comment by devemux86** [comment]
>It should be fixed.

You mean in `Viewport` or in the classes which use it?

**Comment by andreynovikov** [comment]
In `LocationOverlay`. I just overlooked this use. As you can see in the code, screen coordinates are transformed forth but not transformed back after position clipping. But it should be better to remove transform and just overwrite clipping.

**Comment by devemux86** [comment]
The thing is that changing how the API behaves will break users apps.

**Comment by devemux86** [comment]
Also both methods are already in use in VTM classes without issues, so need to think how to best handle this.

**Comment by andreynovikov** [comment]
But what if API _is_ broken? You can not have different coordinate origin in to/from methods. You have to decide where to place 0,0 and make this uniform.

**Comment by devemux86** [comment]
So the example in #81 works if the screen point gets transformed before its use:
```java
screenPoint.x += map.getWidth() / 2;
screenPoint.y += map.getHeight() / 2;
```
I wouldn't call it "broken". It's kind of differently implemented in the two directions (probably not at the same time).

How about enhance the API with additional methods covering all options and enriching the documentation too?

**Comment by andreynovikov** [comment]
Can you prototype the API for me? I can implement it but can not think of proper method names to overcome current situation.

**Comment by devemux86** [comment]
Same named methods with an extra boolean `screenCenter` parameter.
Existing methods could have different default values for compatibility.
What do you think?

**Comment by devemux86** [comment]
`Viewport` already knows the map width and height so transformations shouldn't be difficult.

**Comment by devemux86** [comment]
See commit 26a0179a7ae862a84ad75d63f229f9f74068f217 in `issue_81` branch for a simple API enhancement.

**Comment by devemux86** [comment]
Closing this, as implemented via c4d7b30f0d6e9530bbbb5776300d5a2cfe547a24.

**Pull request closed without merging**
