### PR TITLE
Added MergeMapPositionAnimationsActivity to samples

### PR DESCRIPTION
**Pull request by mathieudebrito**
This example demonstrate that MapPositions does not merge during animations

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!
- Better name the class to simpler `MapPositionActivity`?
- Also it could extend the `SimpleMapActivity` in order to avoid duplicating the layers code (see `LocationActivity`)

**Comment by mathieudebrito** [comment]
You're right, I'll do that !

**Comment by mathieudebrito** [comment]
Changes made

**Comment by devemux86** [comment]
Squashed and merged via 2573e458d5479919b50a8b1a1bab910da42893d9 with some improvements.

**Pull request closed without merging**
