### PR TITLE
Add support for layer groups

### PR DESCRIPTION
**Pull request by andreynovikov**
Extend layers interface to add support for layer groups. The benefit is that layers can be added to particular sets without any overhead on further layer processing.

### CODE REVIEW

**Comment by devemux86** [comment]
Can you rebase your branch onto latest `master`?

**Comment by devemux86** [comment]
Can you explain in more detail what's the actual use of this implementation?
i.e. the life cycle of the calls to understand how it improves existing infrastructure.

**Comment by andreynovikov** [comment]
Assume, you have basic setup:
1. Base vector layer
2. Labels
3. Buildings
4. Paths and markers
5. Grids and scale bars.

Then user wants to add bitmap tile map on top of vector data. It should go above labels, but below buildings. Then user loads KML file with paths and markers. They should go below grids. Then user disables buildings, layer is removed. Then he decides to return them back. New buildings layer should go below paths and markers, not on top of layer list. And so on...

**Comment by devemux86** [comment]
Thanks!

Rebased and merged via 89198c1a3074b2ce843c4b75f6c8e1e08ab25a25.

`LabelLayer` is not visible below translucent buildings, so I put it back on top.

**Pull request closed without merging**
