### PR TITLE
Clustered itemized layer - legacy standalone classes

### PR DESCRIPTION
**Pull request by nebular**
Itemized Layer with the ability to cluster markers

### CODE REVIEW

**Comment by devemux86** [comment]
Current structure has the nice advantage to not break API and introduce harmlessly a new feature.
At the end we could extend `marker` classes to avoid duplicate code and possibly merge the packages or even modify `marker` classes.
But keeping things simple, let's review the `markercluster` first and then decide for the best process.

BTW seeing the `ClusteredMarkerItem` comments, the regular `MarkerItem` may be referred as immutable but we have removed the `final` from its elements, e.g. can change position easily.

**Comment by nebular** [comment]
> PR structure has the nice advantage to not break API and introduce harmlessly a new feature.
We could extend marker classes to avoid duplicate code and probably merge the packages or even modify marker classes.

That sounds great. Maybe the ideal thing would be, after validating this works properly, to implement it as an alteranative renderer for ItemizedLayer, as 99% of the functionality is there. But as you say keeping things simple and reviewing this is the best thing for now.

**Comment by devemux86** [comment]
After merging PR #295 with draw circle..

I cherry-picked from here the cluster commit and merged it in new [cluster](https://github.com/mapsforge/vtm/tree/cluster) branch.
So you can try the marker clustering already in there.

Will need proper review to see how can best integrated to the library.

**Comment by nebular** [comment]
Thanks for considering my contribution. If I can be of any help please tell. BTW - I've discovered a bug, the bitmap database is declared static (my first version didn't allow change colors so back then it was right), so the line 504 in ClusteredMarkerRenderer says:

`    private static Bitmap[] sClusterBitmaps = new Bitmap[CLUSTER_MAXSIZE + 1];
`
and should say

`    private Bitmap[] sClusterBitmaps = new Bitmap[CLUSTER_MAXSIZE + 1];
`

Do you want me to change it? If yes, should I checkout the branch and modify it there? 

Regards!

**Comment by devemux86** [comment]
> If I can be of any help please tell.

Do you think it's possible to provide an implementation with cluster classes as extensions of regular ones?
They can be hosted side by side those under `marker` sub-package and contain **only** the overridden methods needed for clustering.

Have not studied in detail the code yet, so this is just a thought to speed-up the review.
That would save the time of compare and filter the duplicate code. :slightly_smiling_face: 

> Do you want me to change it? If yes, should I checkout the branch and modify it there?

Or else you could create a PR on `cluster` branch with any changes you see appropriate.

**Comment by devemux86** [comment]
See more simple implementation in #310.

**Comment by devemux86** [comment]
Thanks!
Merged via 4b30ca324296f035c1f5333b0b9307ab32b5747b with improvements via 28961caa79a127903fb4451fc1e3291d459713dd.

**Pull request closed without merging**
