### PR TITLE
ItemizedLayer, PathLayer API enhancements

### PR DESCRIPTION
**Pull request by Pedinel**
This changes allows ItemizedLayer to add multiple Items of any collections.

Explanation:
if I have this code (CustomMarkerItem extends MarkerItem):
`ItemizedLayer<MarkerItem> markerLayer = new ItemizedLayer<>(map, symbol);
LinkedList<CustomMarkerItem> myIconsList = new LinkedList<>();
`

I can't add my Icon list to the ItemizedLayer:
`markerLayer.addItems(myIconsList);`

### CODE REVIEW

**Comment by devemux86** [comment]
I find existing API working correctly with e.g.:
```java
ItemizedLayer<MarkerItem> markerLayer = new ItemizedLayer<>(map, symbol);
LinkedList<MarkerItem> markerItems = new LinkedList<>();
markerLayer.addItems(markerItems);
```

**Comment by Pedinel** [comment]
yes, but if you have `LinkedList<CustomMarkerItem> markerItems = new LinkedList<>();` you can't call `markerLayer.addItems(markerItems);`

Its the same for PathLayer, you can't call `pathLayer.setPoints(points)` for `LinkedList<CustomGeoPoint> points = new LinkedList<>();`

**Comment by devemux86** [comment]
Why not using lists with base class generics?
(see the example above)

**Comment by Pedinel** [comment]
In my code, Im using a CustomMarkerItemBase with an abstract method "triggerAction()", that is triggered on Tap event from ItemizedLayer<CustomMarkerItemBase>.

Another classes hold different Lists per type, because I can enable/disable some Icons on the map. So, If I wanna display only Items created by user, or items downloaded from server, I just add the specified List of items to the layer

I cant hold the generic class "MarkerItem" because I need to call another methods varying on Class type.

The same for PathLayer. I add Different type of points to the same layer, and I use a custom Base GeoPoint with implemented methods that I need.

**Comment by devemux86** [comment]
Ok I understand, but see why the library build [fails](https://travis-ci.org/mapsforge/vtm/builds/171984235) now.

`PathLayer`(s) can use some improvements.

`ItemizedLayer` is already built with the extension in mind:
```java
class ItemizedLayer<Item extends MarkerInterface> extends MarkerLayer<Item>
```
Isn't sufficient to use?
```
ItemizedLayer<CustomMarkerItem> markerLayer = new ItemizedLayer<>(map, symbol);
```

**Comment by devemux86** [comment]
Thanks!
I merged `PathLayer` API enhancements via 422d81d66580d9723ee616b7d6b4258e9be74a44 and `ItemizedLayer` via 1d7afaf8de77e21eb2ebea2afcea8878e14e3b93.

Not added `<T extends Item>`, as `Item` already extends `MarkerInterface` and is used everywhere in the class.
Are they ok?

**Comment by Pedinel** [comment]
Yes, that works for me!. Im having trouble with Travis-CI (Im not familiar with it) and I couldn't solve the conflicts.

**Comment by devemux86** [comment]
Ok we can close this then.

Regarding Travis, it's a useful indicator when something is wrong with library building.
You can get the same results, before pushing a commit, if you perform a full rebuild locally.

About pull requests, it's [recommended](https://help.github.com/articles/about-pull-requests/) for your convenience using a topic branch for each pull request.

**Pull request closed without merging**
