### PR TITLE
move GDX models from vtm-playground to vtm-themes

### PR DESCRIPTION
**Pull request by Gustl22**
See #570.

### CODE REVIEW

**Comment by devemux86** [comment]
`GdxModelLayer` doesn't seem to be used anywhere, so better not include "test" models in themes?

**Comment by Gustl22** [comment]
`GdxModelLayer` will be featured. But "test" model isn't needed...

**Comment by Gustl22** [comment]
I don't wanted to have two different locations. So either we delete "test" then or have support for both platforms (if android has been added)...

**Comment by devemux86** [comment]
"test" can be moved to [original location](https://github.com/mapsforge/vtm/commit/2e9b6bf42c1d40992fa0555923a86604f7665271) for storage and `GdxModelLayer` can remain as-is with hard-coded paths since it's unused?

**Comment by Gustl22** [comment]
I don't get your intent. I make preparations for `GdxModelLayer`, too. This will be used like you can see in #570. There it is as dynamically as the `Poi3DLayer`. So why make a difference? And then "test" should be available for all platforms or non of them...

**Comment by devemux86** [comment]
In a library we cannot have "test" resources, those are only for samples.
If "test" can be usable for a role, then should be renamed for that role.
Users cannot imagine for what purpose to use a "test" named model.

**Comment by Gustl22** [comment]
So I leave "test" model in playground and later add an example in Gdx3DTest. (But it won't be on Android then...)

**Comment by devemux86** [comment]
I meant that if "test" is really usable model then we can rename it first and then include it in themes.
What is its purpose?

**Comment by devemux86** [comment]
> So I leave "test" model in playground and later add an example in Gdx3DTest. (But it won't be on Android then...)

That seems the most clear solution for now.

**Comment by Gustl22** [comment]
"test" model reverted.

**Comment by devemux86** [comment]
Thanks!
Merged via 272ce1d9b697afc7f7827d80b8414875cea71247.

NOTE:
I created [vtm-models](https://github.com/mapsforge/vtm/tree/master/vtm-models) module via #580 to better host them.

**Pull request closed without merging**
