### PR TITLE
Native gestures

### PR DESCRIPTION
**Pull request by andreynovikov**
This PR fixes gesture handling like the problem with long press still firing on drag zoom, lets adding new gestures and introduces two new gestures: triple tap and two finger tap for zoom out (last one is commonly used in popular mapping applications).

I need help in checking it on other platforms. For instance I do not know what to do with this:
https://github.com/mapsforge/vtm/blob/master/vtm-gdx/src/org/oscim/gdx/LayerHandler.java

Looks like it can be removed the same way as for Android but I am not sure. Can someone look at this PR on iOS and Windows?

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

Will check it.
I see Travis failing, do you have any more work?

**Comment by devemux86** [comment]
The Android overlay gestures don't work now (e.g. `MarkerOverlayActivity` in `vtm-android-example`).
Why the remove of Android `GestureHandler`?

Regarding the `LayerHandler` it manages the overlay gestures on GDX platforms, see #151 (e.g. `MarkerLayerTest` in `vtm-playground`).

**Comment by devemux86** [comment]
BTW since all those are core features we should preferably implement / integrate them step by step.
Right now there are changes in too many places and not easy to examine which broke what functionality. :slightly_smiling_face: 

For example separately:
- Fix long press
- Add triple tap (what it does in VTM?)
- Add two finger tap zoom out
- Remove carefully redundant classes (after thorough testing)
- ...

**Comment by andreynovikov** [comment]
This can not be done in steps as this is all about replacing Android gesture handler.

I'll have a look at `MarkerOverlayActivity`

**Comment by devemux86** [comment]
Well I guess first we need to discuss why we need to replace something.. we don't even have an open issue for a gesture bug?
And then proceed fix by fix and gesture by gesture. No need all done simultaneously.
That certainly makes our lives difficult and the testing / integration taking forever.

**Comment by andreynovikov** [comment]
What exactly does not work in `MarkerOverlayActivity`? It sets marker and shows toast.

**Comment by devemux86** [comment]
The overlays have gestures managed in Android by `GestureHandler` and `MapEventLayer` handles the map events (not overlays).

Now first one or two tapped markers work (changed icons) and then the with the rest nothing.

**Comment by devemux86** [comment]
- I updated the marker samples on Android and Desktop to include also overlay long press events
- At Android samples I added also events on map (tap + long press)
- In #250 I pushed a fix for the quick scale vs long press issue

**Comment by andreynovikov** [comment]
I have fixed all issues. The major problem is that events are reused. Both by Android framework and VTM. It leads to double copying of objects to make them available for reference in future. I do not like this approach at all. So if you wish not to merge this I will just implement everything I need in my application using native Android methods.

**Comment by devemux86** [comment]
Two cases here:
- Generic: any major / core changes should be [discussed](https://github.com/mapsforge/vtm/blob/master/.github/CONTRIBUTING.md) first for all to understand why / how we should modify some library's API or behavior. Also PRs should contain the absolutely minimum changes per fix, improvement, one feature each time, i.e. better multiple small PRs than one complicated and difficult to debug. :slightly_smiling_face: 
- Specific: since VTM is a multi-platform library, some things live in the core (like the map gestures) and some are exposed via each platform's native API. For example we handle differently the overlay gestures on Android and libGDX in the two handlers, but the events themselves come from the platforms, e.g. we don't re-write the marker long-press gesture or delay from the start.

So here we need first to clarify what we want to fix or change or add and then go for it.
- Are there any bugs in gestures (after #250)? We should fix them separately.
- Are there any duplicated uses? We should report, check them and examine why this happens.
- Which are in detail the new gestures we want to introduce? We could discuss the procedure and add them one at a time, for better testing.

Finally VTM (like Mapsforge) is an open source library affecting many users. It's not meant to satisfy only some developers needs, but all who use it. And they use it in many platforms not just Android. It should progress in time and with good testing without haste.

**Comment by devemux86** [comment]
@andreynovikov really appreciating your contributions :slightly_smiling_face: best to integrate it as a 2nd `MapEventLayer`.
We leave existing and side classes unmodified and set a selection in `MapView` initialization.
It's been done before and would permit us having convenient progress & testing by all users.

**Comment by devemux86** [comment]
I have a first draft of the two `MapEventLayer` working quite well, will push probably later.

BTW testing the GDX events with the PR, I see them coming two times, e.g. `MarkerLayerTest`.

**Comment by devemux86** [comment]
Hmm tried the PR in latest VTM and GTW complains (see [Travis](https://travis-ci.org/mapsforge/vtm/builds/178818027)):
```
No source code is available for type java.util.TimerTask
No source code is available for type java.util.Timer
```

**Comment by andreynovikov** [comment]
How can it be? It was introduced in Java 5:
http://docs.oracle.com/javase/7/docs/api/java/util/TimerTask.html

**Comment by devemux86** [comment]
GWT includes a library that emulates a subset of the Java runtime library, e.g. for [java.util](http://www.gwtproject.org/doc/latest/RefJreEmulation.html#Package_java_util).

Wondering if we can exclude a class via the Gradle gwt plugin.

**Comment by andreynovikov** [comment]
It looks like VTM has some kind of cancelable tasks:
https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/utils/async/Task.java
Didn't know that. If they can be post delayed it should be better to use them for consistency.

**Comment by devemux86** [comment]
Indeed, will you make changes?
Then please do them in [issue_249](https://github.com/mapsforge/vtm/tree/issue_249) branch's [MapEventLayer2](https://github.com/mapsforge/vtm/blob/issue_249/vtm/src/org/oscim/layers/MapEventLayer2.java) which contains the PR.

**Comment by andreynovikov** [comment]
Ok

**Comment by devemux86** [comment]
There are also some `post` methods in `Map` class that could be used.

**Comment by andreynovikov** [comment]
Success: https://github.com/mapsforge/vtm/pull/260

**Comment by devemux86** [comment]
Thanks!
Squashed and merged via 71f7c45b21fe1e426fdf50ee2a160f83fcbcaca7.

**Pull request closed without merging**
