### PR TITLE
Port GL30 from libGDX

### PR DESCRIPTION
**Pull request by Gustl22**
Now the gl30 interface (called GL3 to avoid unnecessary name conflicts).
Unfortunately GDX does not seem to support WebGL 2 with GWT. Or I missed something.
Can leave in separate branch again.

### CODE REVIEW

**Comment by devemux86** [comment]
Merged in branch [issue_646](https://github.com/mapsforge/vtm/tree/issue_646).
Can follow GL30 progress in #646.

Renamed interface to `GL30` for consistency with upstream.

**Comment by devemux86** [comment]
?

**Comment by Gustl22** [comment]
Sorry, my fault. I deleted ref branch and PR was closed :see_no_evil:

**Comment by devemux86** [comment]
Closing since it's merged in its relevant branch.

**Comment by devemux86** [comment]
Thanks, merged via f6f00c25211e7765fc3bcf1b68e54963aca7fe3e.

**Pull request closed without merging**
