### PR TITLE
Layer.setEnabled (false) has been ignored.

### PR DESCRIPTION
**Pull request by Longri**
This PR treats the layer.enabled flag.

As an example, you can turn the BuildingLayer on or off in the Playground Project by pressing the 'B' key!

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!
Need to think a little the implementation.

For example why the need of a new handler, couldn't we solve its need without it?
Also `Layers` could need more work, e.g. there are unbind also in `set` method.

**Comment by devemux86** [comment]
Ok I simplified a bit the concept, will do the merge later.

**Comment by devemux86** [comment]
Thanks!
Merged via 9fff945978ee3456265917fc3088bacd7e612ed3 and simplified via 8ab21955007ea37a33d91fb16f7f535749dde0de.

@Longri please see too that all work fine.

**Comment by Longri** [comment]
looks good, thanks

**Pull request merged**
