### PR TITLE
done: /* FIXME This work only with one TextureAtlas per SymbolBucket */

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by Longri** [comment]
#301 
I have test the last 2h and can't see any side effects!

But maybe copy the AtlasMultiTextureTest to Android and check on this!

**Comment by Longri** [comment]
No conflicts with #294

**Comment by devemux86** [comment]
Ok will review it after #304 for using the updated packer.

**Comment by Longri** [comment]
I will check, but I think that this PR will solve the bug that you see on #304

**Comment by devemux86** [comment]
Are they supposed to be used together?
Texture atlas packer worked before and I thought that in #304 we have just an improved implementation.

**Comment by devemux86** [comment]
Merged in [issue_303](https://github.com/mapsforge/vtm/tree/issue_303) branch for further testing.
I added also an Android similar example.

- On Android the green background is not visible
- And we have the double textures issue of #311

android

**Comment by devemux86** [comment]
The double textures issue was fixed through #311 and I merged the fix in [issue_303](https://github.com/mapsforge/vtm/tree/issue_303) branch too.

**Comment by Longri** [comment]
fix at #313

**Comment by devemux86** [comment]
Thanks!
Merged via 5480cd6df8321914cad425ec5dff01f19c18fcb0.

**Pull request closed without merging**
