### PR TITLE
GL20 improvements

### PR DESCRIPTION
**Pull request by Gustl22**
remove getShaderSource(),
remove non interface methods from lwjgl,
format

### CODE REVIEW

**Comment by devemux86** [comment]
- Why remove missed implementations?
(sometime can implement them)
- What bothers the extra methods in `LwjglGL20`?
(should be similar with upstream for maintenance convenience)

**Comment by Gustl22** [comment]
We should either:
- remove methods that aren't usable on all backends. Can't use them in library (except with `QUIRKS` rules)
- or implement all methods from [GDX](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/GL20.java) interface and `throw new UnsupportedOperationException("unsupported, won't implement");` where needed.

**Comment by devemux86** [comment]
> remove methods that aren't usable on all backends.

Each platform has its own implementation. Cannot limit the library because of one platform.
But here all removed methods contain "missing implementation", not impossible implementation. So they're more like the multiple TODO in `vtm-web` for various features expecting implementation.

Cannot understand the 2nd comment too. We should add functionality when is needed.
Removing it, if there is no problem, does not help in any possible workflow.

**Comment by Gustl22** [comment]
> We should add functionality when is needed.

You answered yourself. Consequence is, if it's not needed we should remove it from `LwjglGL20`. 
Or to be consistent add functionality to all platforms. (There are many methods which aren't used)
Sometimes like this, sometimes like that is not a solution.

So would you agree, if I add missing methods to interface then?

**Comment by devemux86** [comment]
> Consequence is, if it's not needed we should remove it from LwjglGL20.

`LwjglGL20` comes from libGDX, so to better maintain it, we can leave it synchronized with upstream.
There was never any problem so far, if it has some more methods from its parent!

> So would you agree, if I add missing methods to interface then?

If we need them for a feature, then we can add them one-by-one when that feature is introduced, so can be tested right away.
Like was done already, with implementations where we can test them, mostly on Android and Desktop, leaving the other platforms with TODO placeholders.

**Comment by Gustl22** [comment]
> If we need them for a feature, then we can add them one-by-one when that feature is introduced, so can be tested right away.

If adding gl30 I will not only add the methods which are used. With every new feature the developer has to go through the interface and has the work again.
I bet not all interface methods were tested when they were introduced, especially not those which aren't used...

**Comment by devemux86** [comment]
This PR is about GL20, for other versions can see them and discuss how to properly introduce them - without causing problems to library users - on its own forum topic or issue?

**Comment by Gustl22** [comment]
Only wanted to give an example. But I see no difference to adding the remaining methods of gl20.

**Comment by devemux86** [comment]
Still cannot understand what exactly we discuss here. :confused: 

This PR removes methods, which haven't caused any problems so far.
We should clear that and then see what can be done with additions.

**Comment by Gustl22** [comment]
I want consistency through all backends. That makes it easier and well-arranged to maintain the code.

**Comment by devemux86** [comment]
Sorry but consistency for the sake of consistency won't suffice.
Extensive testing with easy maintenance, so to not break library behavior, should be our primary goal.

Like mentioned, third-party classes should exist as came from upstream (even their methods order), so to easily compare their external progress and adjust them accordingly.

**Comment by devemux86** [comment]
Adding our new methods _at class end_, can work, heavily modify them, will not.

**Comment by Gustl22** [comment]
> Which one?

the vtm GL interface for example with [gdx](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/GL20.java)

**Comment by devemux86** [comment]
Upstream classes may have changed, that means we may missed new functions. Many times would need to synchronize ours. That's why we shouldn't remove anything for easy maintenance.

**Comment by Gustl22** [comment]
Thats why I asked this:

> So would you agree, if I add missing methods to interface then?

**Comment by devemux86** [comment]
Let's see it in action. :slightly_smiling_face:

**Comment by devemux86** [comment]
But "missing implementation" is a better message.

**Comment by devemux86** [comment]
If the code comes from libGDX, let's use it without modifications then. :slightly_smiling_face:

**Pull request closed without merging**
