### PR TITLE
repopulateCluster() is called with different scales

### PR DESCRIPTION
**Pull request by wolfgang-ch**
`mScaleSaved` is log2 smaller than `scale` but `repopulateCluster()` is called with both variables

This fixes the bug that subsequent calls to `populate()` will display the markers "correctly" and it will not first put all markers into one single cluster and when zoomed, they are unclustered.

### CODE REVIEW

**Comment by devemux86** [comment]
Cannot be merged 'as is' because commits history causes a mess in repository.

Please try following pull requests [documentation](https://help.github.com/articles/about-pull-requests/) for your convenience and ours:
_"If you're working in the shared repository model, we recommend that you use a topic branch for your pull request. While you can send pull requests from any branch or commit, with a topic branch you can push follow-up commits if you need to update your proposed changes."_
Having a single commit in your topic branch with the changes (instead of multiple master merges) will lead to faster review and merge.

**Comment by wolfgang-ch** [comment]
I read your comment just now, I will recommit it

**Comment by wolfgang-ch** [comment]
replaced with new pull request https://github.com/mapsforge/vtm/pull/381

**Comment by devemux86** [comment]
> I read your comment just now, I will recommit it

Thanks!

**Pull request closed without merging**
