### PR TITLE
Graphics API: draw circle

### PR DESCRIPTION
**Pull request by nebular**
- Implements drawCircle() in Canvas & platform classes
- Android drawCircle is tested and working
- IOS, GWT, AWT are not tested

### CODE REVIEW

**Comment by nebular** [comment]
Trying to create my first PR on VTM

**Comment by devemux86** [comment]
Related to #92.

**Comment by devemux86** [comment]
Thanks!
Merged via 67afa0b7ab2b75a197cb629e5a5951c938e8ef81.

**Comment by devemux86** [comment]
@Longri can you handle the `IosCanvas.drawCircle`?

**Comment by Longri** [comment]
Yes

**Comment by Longri** [comment]
is there any test project to check the right drawing!

**Comment by devemux86** [comment]
There is the [cluster](https://github.com/mapsforge/vtm/tree/cluster) branch which uses the `drawCircle` in the clusters.
It has an Android example, I suppose would need to make it for iOS too for testing.

**Comment by Longri** [comment]
Is there correct, I just have no Android on hand!
screen shot 2017-03-01 at 12 53 49

**Comment by devemux86** [comment]
Yes that's the rendering.

**Pull request closed without merging**
