### PR TITLE
Add fling animation for rotation and scale

### PR DESCRIPTION
**Pull request by Gustl22**
Animator and MapEventLayer
* add fling rotation
* add fling scale

Useable with `Animator2Activity` on Android. May extendable to Desktop/Web.

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, seems very nice!
Merged via 3ed6c43161c63ea434554d43d30685477c0e0a1c.

**Comment by devemux86** [comment]
I have seen a strange side-effect with fling on rotation in some cases.
If do a fast clockwise rotation gesture to achieve e.g. ~360°, then the rotation happens but ends with counterclockwise rotation!

**Comment by Gustl22** [comment]
Thanks, will check that!

**Comment by Gustl22** [comment]
Ok, I checked it on emulator, phone and tablet, but never could reproduce that effect. 
Maybe it happens in a special initial position(?). Does it always happen on clockwise ~360° rotations?
A good place to debug would be the in Animator2s `updateAnimation` and print out the `valueDelta`. If they switch sign, something could be wrong with `DragForce` calculations. Otherwise `rotateMap` needs other input values (e.g. mod 360?)...

**Comment by devemux86** [comment]
> Does it always happen on clockwise ~360° rotations?

Could not reproduce it with counterclockwise gesture.
And with clockwise need to perform a fast fling and doesn't happen always.

> print out the valueDelta

Indeed if print this [valueDetla](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/map/Animator2.java#L281), then when that happens it prints negative values for clockwise gesture!

**Comment by Gustl22** [comment]
Sorry couldn't reproduce that, did you try other devices? 
Maybe you can give me the parameters (`angularVelocity`, `pivotX`, `pivotY`) of `animateFlingRotate` function, when problem appears. So I can test it. Or maybe can help me with detecting the problem 😌

**Comment by devemux86** [comment]
I'll try on other devices too.
It's certainly reproducible at least here, here are the parameters when happens:
(angularVelocity, pivotX, pivotY)=(-39.735355, -25.531921, -17.967896)
Doing clockwise rotate gesture, the `angularVelocity` is positive when works and negative when it doesn't.

**Comment by Gustl22** [comment]
Now I could reproduce your issue, it's when you rotate more than ~180° and then do the fling. It seems that the rotate tracker does not process it the right way. For me it happens in both directions. Will try to fix that.

**Comment by devemux86** [comment]
I created #500 to check it.

**Comment by boldtrn** [comment]
Thanks for the awesome work @Gustl22. I tried the new samples. I like the scale fling. The rotation fling is a bit sensitive IMHO. I think the idea for this is to spin an actual globe? 

I think a very strong rotation fling shouldn't be more than 360°. A medium strong fling shouldn't be more than 180°. From a usability perspective, when would I ever want the map to spin 5 times except to play around? I know Google Maps also spins multiple times, but to be honest I personally don't think this is especially helpful animation. I found myself messing up the map pretty badly. But this is only my opinion, I didn't run any UX studies on this ;).

**Comment by devemux86** [comment]
All `Animator2` flings seem a bit sensitive and like kinetic scroll takes much time to decelerate.
Don't know if it's useful to allow users to define how much sensitive those motions are?

**Comment by Gustl22** [comment]
Thanks for feedback!
I myself am a friend of have much impact with less work. Especially on touch devices fling moves facilitate actions, you only could reach with a mouse.
You're right, you won't need to spin around 5 times. But it makes fun, e.g. for special places/buildings to watch them rotating 😆 
I took a DIN A paper on a table out of wood as reference, and you won't get more than 720° turns. So rotation fling seems a bit too impulsive.
For me it's important to **keep start velocities** with `flingfactor`(or pretty similar) and only change friction values. So the speed keeps equal to speed of moving your fingers. In better words: input speed of fingers should match start speed of fling, to ensure a smooth transition (So there's not much scope). But you could slightly adapt them, if they don't exactly match (maybe rotation fling(?)).

> takes much time to decelerate.

It's kind of a compromise. If I set friction too high, you have to swipe 5 times, before you reach a reasonable distance. But you're invited to play with the values.

> Don't know if it's useful to allow users to define how much sensitive those motions are?

If really needed should make friction parameters public. Wouldn't bother someone, I think...

**Comment by boldtrn** [comment]
> You're right, you won't need to spin around 5 times. But it makes fun, e.g. for special places/buildings to watch them rotating laughing

Yes I agree, it's fun :).

Personally I prefer precision over sensitivity. When doing a fling zoom, if often did a zoom+rotation, which completely messed up the map, I might be clumsy but this happens pretty easy :).

 > only change friction values

Yes maybe a higher friction value would be prefered by me. But I also understand that everyone has a different opinion on these kind of things.

> input speed of fingers should match start speed of fling

Good point, this seems valid.

> If really needed should make friction parameters public.

I like that :).

**Comment by devemux86** [comment]
> If really needed should make friction parameters public.

> I like that :).

In such case, a good documentation should be added to parameters so that users can understand what each value changes and how. 🙂

**Comment by Gustl22** [comment]
> When doing a fling zoom, if often did a zoom+rotation

I know, what you mean. This suffers from rotate/scale detection, and could be improved. But this is another problem area (or better improve interaction of these two gestures in Animator).

I'll do a PR with updated values and documentation, and you can rewiew them.

**Comment by devemux86** [comment]
> When doing a fling zoom, if often did a zoom+rotation

> I know, what you mean. This suffers from rotate/scale detection, and could be improved. But this is another problem area (or better improve interaction of these two gestures in Animator).

That should be relevant with `Animator2` since regular `Animator` does not show any issues.

**Comment by Gustl22** [comment]
Yes sry, meant `Animator2` as `Animator` does not use these.

**Comment by Gustl22** [comment]
@devemux86 sorry that I come up with this again. Can we enable `Animator2` in all our sample activities? Not necessarily have to change it in lib. But I think it is more comfortable to use :see_no_evil:

**Comment by devemux86** [comment]
Not sure what you mean.
When doing development, everyone can enable `Animator2` via its simple flag.
Activating it for all samples would give users different first impression vs library defaults?

**Comment by devemux86** [comment]
Could make `Animator2` default in library level, sometime if is mature enough, but prefer to never hurry with core changes. :slightly_smiling_face:

**Pull request closed without merging**
