### PR TITLE
Render-theme docs

### PR DESCRIPTION
**Pull request by Gustl22**
I adopted the basic structure from Mapsforge Render-Themes. And I tried to explain some difficult attributes.
@devemux86: You can have a look, if it's all correct? Especially the style menus may work different.

### CODE REVIEW

**Comment by Gustl22** [comment]
BTW: you can always add commits to my repos on PRs, e.g. if it's more comfortable than adding a branch or need of doing a quick improvement.

**Comment by devemux86** [comment]
Thanks for the needed documentation!

Quick notes:
- I transferred our "style menu" work from Mapsforge to VTM, so should work similarly.
- Priorities (unfortunately) were implemented [differently](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlMapsforgeThemeBuilder.java#L996-L997) in the two map engines:
**Mapsforge**: higher priorities are drawn first (0 = default priority)
**VTM**: lower priorities are drawn first (0 = highest priority)

**Comment by Gustl22** [comment]
Thx! I changed "priority" description :)

**Comment by devemux86** [comment]
Thanks!
I added a link in repository main page.

**Pull request merged**
