### PR TITLE
Playground: replacing dead ocsim with osm bitmap

### PR DESCRIPTION
**Pull request by telemaxx**
and adjustments for new MarkerInterface

### CODE REVIEW

**Comment by devemux86** [comment]
It is simpler to make the minimum changes and just replace the tile source in the existing [MarkerLayerLabelsTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MarkerLayerLabelsTest.java).

(like in [MarkerLayerTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MarkerLayerTest.java#L54-L58))

**Comment by telemaxx** [comment]
I have not changed that much. seems so, that eclipse have done some reformating. I try to revert that.

**Comment by devemux86** [comment]
Just change the tile source in the existing class (it's 5 lines of code).

**Comment by telemaxx** [comment]
close for now

**Pull request closed without merging**
