### PR TITLE
Texture atlas: use bitmap packer based on libGdx PixmapPacker

### PR DESCRIPTION
**Pull request by Longri**
When looking at the error in #301 , I have seen that the Atlas Images were not always optimally packed. Therefore I looked at the PixmapPacker of LibGdx and ported this to a use with Bitmap's!

### CODE REVIEW

**Comment by devemux86** [comment]
@Longri can you check the PR state?
I find it not working correctly on `AtlasMarkerLayerTest` and `AtlasMarkerLayerTest` samples.
When pressing a marker then the same icon is used instead of the focus one.

**Comment by Longri** [comment]
You are right, this only occurs if the Bug #301 not fixed!
In attempting to calculate the optimal size of the atlases, I have lost.
Therefore two small atlases will created. With two atlases it will not work without fix the bug #301.
I will rework the calculation of size and choose a POW2 size which is better for OpenGl!

**Comment by Longri** [comment]
now it will calculate correct! Thanks for the hint!

**Comment by devemux86** [comment]
Thanks!
Merged via 23d34fa00ad9772b92f7f0f83842b65fac7afb4b.

**Pull request closed without merging**
