### PR TITLE
Fix the horizontal inversions on 3d models

### PR DESCRIPTION
**Pull request by schedul-xor**
Painted car models green on the right side. Displayed models looks like the left half is painted green. Models generated by fbx-conv seems to be displayed with horizontally inversion.
image

Used libgdx-fbxconv-gui previews as reference behaviour.
https://github.com/ASneakyFox/libgdx-fbxconv-gui

libgdx-fbxconv-gui shows that the right half of the running car is painted green.
vtm-playground shows that the wrong half of the running car is painted green.

### CODE REVIEW

**Comment by devemux86** [comment]
_Side note: please avoid committing new test variables, so can have only the needed changes.
e.g. `build.gradle` and `GdxPoi3DTest` seem no need any changes._

**Comment by schedul-xor** [comment]
The car object placement seems to be commented out in `GdxPoi3DTest`. Reverted `build.gradle`.

**Comment by schedul-xor** [comment]
Reading libgdx-fbxconv-gui source code, I found out that there are some differences between vtm-gdx-poi3d and libgdx-fbxconv-gui on model-loading.

libgdx-fbxconv-gui is reading models from assets like this (https://github.com/ASneakyFox/libgdx-fbxconv-gui/blob/master/core/src/asf/modelpreview/ModelPreviewApp.java)

	private AssetManager assetManager;
	private G3dModelLoader g3dbModelLoader;
	private G3dModelLoader g3djModelLoader;
	private ObjLoader objLoader;

        public void create(){
		objLoader = new ObjLoader();
		g3dbModelLoader = new G3dModelLoader(new UBJsonReader());
		g3djModelLoader = new G3dModelLoader(new JsonReader());
        }

	private Model loadModel(File f) {
		if (f == null) {
                    // Not important
		} else {
			String absolutePath = f.getAbsolutePath();

			if (absolutePath.toLowerCase().endsWith("obj")) {
				return objLoader.loadModel(Gdx.files.absolute(absolutePath));
			} else if (absolutePath.toLowerCase().endsWith("g3dj")) {
				return g3djModelLoader.loadModel(Gdx.files.absolute(absolutePath));
			} else {
				return g3dbModelLoader.loadModel(Gdx.files.absolute(absolutePath));
			}
		}
	}

vtm seems to be loading models using the following code.

    Model model = mAssets.get(poiModel.getPath());

Changing the model reading may fix this issue?

**Comment by Gustl22** [comment]
Indeed, the models are mirror-inverted at x-axis. Using obj loader doesn't solve the problem. So need to fix while loading.

**Comment by devemux86** [comment]
> Indeed, the models are mirror-inverted at x-axis. Using obj loader doesn't solve the problem. So need to fix while loading.

So closing here?

**Comment by Gustl22** [comment]
> So closing here?

Don't know if this was rather an example than a fix ;D

**Comment by schedul-xor** [comment]
Thank you. Forget about it.

**Pull request closed without merging**
