### PR TITLE
Fix fling rotation reverses direction (#500)

### PR DESCRIPTION
**Pull request by Gustl22**
Rotation range normalized to range of (+/-) PI.

See #500

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

- Better move the normalization inside `Animator2` check, since that's the affected gesture.

- Can use a simple normalization like [MapPosition.clampBearing](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/core/MapPosition.java#L194) in [-180°, 180°]:
```java
while (rotateBy > Math.PI)
    rotateBy -= 2 * Math.PI;
while (rotateBy < -Math.PI)
    rotateBy += 2 * Math.PI;
```

**Comment by Gustl22** [comment]
Thanks. Updated PR.
Normalization of `rotateBy` doesn't have an effect on orientation in later used `rotateMap`. But moved it in `Parameters.ANIMATOR2` block, to test. The value was wrong before, but didn't entail any problems as `rotateMap` doesn't care about that, respectively normalizes it later :)

**Comment by Gustl22** [comment]
What I noticed during editing: 
- Does anything speak against moving `FastMath` into `utils.math` package?
- Maybe [MapPosition.clampBearing](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/core/MapPosition.java#L194) could be released in `MathUtils` as `clampDegree(float degree)` or something?

**Comment by Gustl22** [comment]
Sorry if I messed up this PR with radian fixes in `Animator2`. Can start separated PR, if you wish.

**Comment by devemux86** [comment]
Thanks!
Merged via bd9e7d74569d07f087266c6411941e4074041b45.

**Comment by devemux86** [comment]
> Does anything speak against moving FastMath into utils.math package?

Actually all classes in `org.oscim.utils.math` are or derived from libGDX.
Also since `FastMath` is a public util class, need to think more for a package change.

> Maybe MapPosition.clampBearing could be released in MathUtils as clampDegree(float degree) or something?

Nice idea and more clean code!
I put it in `FastMath` which is VTM class and left `MathUtils` with only its own libGDX methods.

**Pull request closed without merging**
