### PR TITLE
CircleBucket (Android): Disable VERTEX_PROGRAM_POINT_SIZE

### PR DESCRIPTION
**Pull request by Gustl22**
Call `gl.enable(VERTEX_PROGRAM_POINT_SIZE);` not valid in OpenGL ES. Caused GL error.
See: https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_cm_spec_2.0.pdf page 64
Related: #305

### CODE REVIEW

**Comment by devemux86** [comment]
What is the exact error in the console so we can test that in emulator or device?

**Comment by Gustl22** [comment]
If place e.g. `GLUtils.checkGlError("MY_ERROR_DESCRIPTION");` right behind the invalid line, get:
```
2018-12-15 16:17:00.687 5218-5253/? E/o*.o*.r*.GLUtils: MY_ERROR_DESCRIPTION: glError 1280
```
which means `GL_INVALID_ENUM`.

Or in Gapid Debugger, I get this, which code means 34370 = 0x8642 = VERTEX_PROGRAM_POINT_SIZE:
```
6317: Error "glEnable"
Invalid enum 34370.
```
(Tested on physical device with Android P)

**Comment by devemux86** [comment]
Cannot reproduce it on emulator, need to make more tests.

**Comment by Gustl22** [comment]
I didn't get the error message on emulator either. But on both Android Devices (Galaxy Tab S3 & Oneplus 6). Maybe cause emulator uses desktop graphics card.

**Comment by devemux86** [comment]
Thanks, merged via e18f3577f04eac695ff1d5c64e0f22310910a74e.

**Comment by devemux86** [comment]
Also confirmed on actual devices.

**Pull request closed without merging**
