### PR TITLE
Make datetime rewritable

### PR DESCRIPTION
**Pull request by schedul-xor**
First of all, Gustl22's shadow expression is awesome. It's shadow is calculated based on sun's position, why can't the time be overwritten? Currently modified `vtm-web-app` to move "inner" time 10 minutes per second in real world.

### CODE REVIEW

**Comment by devemux86** [comment]
Doesn't `Sun` class already allows to change the date?

**Comment by devemux86** [comment]
_Please don't change in same PR a library feature and the samples, those should be examined separately._

**Comment by Gustl22** [comment]
If you mean to change sun position/progress by datetime, then I will implement that, but we shouldn't change `DateTimeAdapter` to hold any value. Except that it wouldn't give the current time anymore. For that you can create your own `DateTime` in your application.

**Comment by schedul-xor** [comment]
@Gustl22 Now I understood I can implement my original `DateTime`. Thank you. Closed.

**Comment by Gustl22** [comment]
If you mean platform specific such as `JSDate` with "original", then yes :)

**Pull request closed without merging**
