### PR TITLE
Enable / improve JNI module

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, seems interesting approach!

Need first to explore how can avoid hosting any external modules.
i.e. access https://github.com/memononen/libtess2 and https://github.com/libgdx/libgdx/tree/master/extensions/gdx-jnigen as submodules (like now) from their repositories where they're maintained and progress continuously.

Furthermore in any moved class we shouldn't make changes, those belong to different PR.

**Comment by devemux86** [comment]
We can review natives build but using their original code since it's offered as independent libs.

**Comment by Longri** [comment]
Which libs do you mean?

**Comment by devemux86** [comment]
Haven't you read my above review?
All details are there from the start. :slightly_smiling_face:

**Pull request closed without merging**
