### PR TITLE
add module 'theme-comparator'

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Very nice!

- How does it work? I use the "Load map file" menu but nothing is loaded (log is empty)
- Better we shouldn't replicate VTM theme assets, but use `vtm-themes` module (like with Mapsforge)

**Comment by Longri** [comment]
Nothing loaded? 
Have you run from Android-Studio, what is the Console-log? 
I have loaded some maps from Mapsforge Server (Berlin, Brandenburg, Germany) but also Maps from 'Freizeitkarte'!

**Comment by devemux86** [comment]
When app starts in AS it shows:
```
[LWJGL Application] DEBUG org.oscim.gdx.GdxAssets - File not found: shaders/line_aa_proj.glsl (Internal)
```
Then trying open [berlin.map](http://download.mapsforge.org/maps/europe/germany/berlin.map) nothing happens.

**Comment by Longri** [comment]
Have you deleted the assets folder? 
The missing shader is inside. 
Maybe you remember, that I have always problems with the asset dependencies from other modules, so I have created a own. 

If you have not deleted this folder, so set the working directory to this folder.

**Comment by devemux86** [comment]
No, haven't modified anything, just pull the PR and run.

_In final version we should anyway keep a clean structure solving any problems, with module dependencies and not duplicated resources, which would need changes in multiple places every time we improve something._

**Comment by Longri** [comment]
Yes, you are right, but I can't!

**Comment by devemux86** [comment]
> Yes, you are right, but I can't!

Ok, I'll check it. :slightly_smiling_face: 

Here in `MapLoader.loadMap` the `Gdx.app.postRunnable` never runs.

**Comment by Longri** [comment]
It's not running, because the Gdx.app is not initiall! 

For first impressions, set the working directory to assets! So the App will run! 

Then I would be very grateful if you can solve the problem with the dependencies.

**Comment by devemux86** [comment]
> For first impressions, set the working directory to assets! So the App will run!

Ok now it runs!

BTW it's often unresponsive with high CPU load logging:
```
[LWJGL Application] DEBUG org.oscim.layers.tile.TileManager - too many tiles 4
```

But a first step is to review the module dependencies & structure for a simpler implementation.

**Comment by devemux86** [comment]
I merged it in [issue_386](https://github.com/mapsforge/vtm/tree/issue_386) branch with some improvements via 1cf4d3a60bf688a36e5d80dcd2c4ac15f40aa900.

@Longri can you check how it plays?
It seems to be a good base for additional work.

**Comment by devemux86** [comment]
BTW don't know if naming `theme-comparator` is convenient, i.e. it has 2 map views and 1 theme, so what does it compare?

**Comment by Longri** [comment]
Yes, it works, but only with the AndroidStudio.
With IntelliJ I have the said dependency problems.

The name ‘ThemeComparator’ was the first one that occurred to me. ’ThemeRepresentationComparator’, was too long for me.


Before I start however the Mapsforge Theme-V4 for VTM readable, I have one more question. Would you like to have your own ThemeBuilder here, or do you prefer one that can read both?

**Comment by devemux86** [comment]
Haven't tried it, since needing Android, the AS seems a natural choice.
Probably some configuration setting, as both have the same base.

BTW also in AS until do a full Gradle build / refresh some resources aren't immediately available (see #205).

Regarding the naming, don't like long names either.
But more questioning the `theme` part, since we don't compare 2 theme files?

> Before I start however the Mapsforge Theme-V4 for VTM readable, I have one more question. Would you like to have your own ThemeBuilder here, or do you prefer one that can read both?

_As always the best is not break existing API since users depend on it._

We can indeed have separate theme parsers depending on loaded theme.
Mapsforge and VTM themes use different schemas, declared in their headers, can use that(?).

Also VTM has special OpenGL directives in themes, while Mapsforge is a separate library with its own rules.
So better for safety to have separate theme readers, it seems more future proof and maintainable.

**Comment by devemux86** [comment]
We can use [Mapsforge](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map/src/main/java/org/mapsforge/map/rendertheme) code for help, though it uses a pull parser.

**Comment by Longri** [comment]
My idea was to copy the XmlThemeBuilder to XmlMapsforgeThemeBuilder and then use it in a Mapsforge theme.

Then I would adapt this bit by bit.

Firstly replace
`private static final String ELEMENT_NAME_MATCH = "m";`
with 
`private static final string ELEMENT_NAME_MATCH = "rule";`

I have here a Perl script, which converts a V4 Theme into a Vtm theme.
I would go through it bit by bit.

**Comment by devemux86** [comment]
Seems good!
Also need to consider Mapsforge specific directives that we have not implemented yet in VTM, like [symbol positioning](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#symbol-positioning), etc.

**Comment by devemux86** [comment]
BTW let's continue themes discussion in #100 for not to be lost here.

**Comment by devemux86** [comment]
Thanks!
Merged via 9c5fd29ff14d56b7e3f94fbc805c68a6f6277e6a with some improvements via 1cf4d3a60bf688a36e5d80dcd2c4ac15f40aa900.

**Pull request closed without merging**
