### PR TITLE
create vtm-ios-example project

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Can you use a different package in `vtm-ios-example`, like `org.oscim.ios.test`?

Also are there example classes in `vtm-ios` which can be removed now?

**Comment by Longri** [comment]
I'll check and commit with removed classes from vtm-ios!

**Comment by devemux86** [comment]
Something else nice would be the `vtm-ios-example` to use the `vtm-ios` natives.
You can check how `vtm-android-example` uses its own via Gradle.
That way the natives should exist in one place in repository, less space and better maintenance.

**Comment by Longri** [comment]
vtm-ios is now a pure library without launcher classes!
vtm-ios-example has no natives and use their from ios-vtm

**Comment by devemux86** [comment]
Thanks!
Merged via 7500ca17118f490c4f928ba380b2dae1ec2adc86.

**Comment by devemux86** [comment]
I cleaned up a bit the `vtm-ios-example` build.gradle.

- In `vtm-ios` build.gradle do we need the `org.oscim.ios.RoboVmLauncher` reference?
- In `vtm-ios-example` build.gradle the `org.oscim.ios.RoboVmLauncher` shouldn't be renamed?

**Comment by Longri** [comment]
I think both can deleted, but I will try it tomorrow and commit if it ok.

**Comment by devemux86** [comment]
I made an [announcement](https://groups.google.com/forum/#!topic/mapsforge-dev/zO0G4-dH680) in the forum for larger user visibility.

**Pull request closed without merging**
