### PR TITLE
Tag transform improvements

### PR DESCRIPTION
**Pull request by Gustl22**
- reverse `output-k`, `output-v` -> `k`, `v`
    `match-k` `match-v` -> `output-k`, `output-v`
- introduce `mRetransformKeyMap` (with swapped keys / values) in `RenderTheme` as replacement for `mTransformKeyMap`.
- refactor `transformKey` to `retransformKey`
- remain `transformTag`, as it will be usable in future use cases, e.g. transform colors.

Related #420.

### CODE REVIEW

**Comment by devemux86** [comment]
The "retransform" term isn't obvious, means nothing and confuses about what actually happens.
All processes are transforms, can use forward / backward, once decided which direction is each.
Why there are `retransformKey` and `transformTag`, different behavior for the two rule types.
They should work in parallel, e.g. if want use the commented transform rules in the two themes.

**Comment by devemux86** [comment]
The theme builder stores the transform rules as declared and then the render theme reverses one map of the two. Why such complexity, can store them reverse from the start. Or even better avoid any reverse and make a proper plan of how the tag transform should work in all cases. Users won't use the transform only with keys but also with keys/values, they expect similar workflow for both cases.

**Comment by devemux86** [comment]
Also if do some testing with the PR can see that `MapilionMvtTest` buildings rendering is now broken.

**Master:**


**Pull request:**

**Comment by Gustl22** [comment]
> can use forward / backward

So why you complain now and didn't made the proposal after I mentioned [this](https://dict.leo.org/german-english/retransform). That's time consuming for me, too.

> Why there are `retransformKey` and `transformTag`, different behavior for the two rule types.
They should work in parallel, e.g. if want use the commented transform rules in the two themes.

I already did that in parallel, but you insisted to make simple step by step PRs. And currently there's no implemented uses case for `transformForwardKey` and `transformBackwardTag`.

> Why such complexity, can store them reverse from the start. 

I explained it already several times, but ok.

We have four cases:
- transformForwardKey: used to transform tile source keys instantly to osm keys (not needed yet).
- transformBackwardKey: used to transform several osm keys to lazy fetch the needed tile values in `BuildingLayer` only.
- transformForwardTag: used to transform tile source tags instantly or in selected use cases to osm tags (needed soon). E.g. to transform colors.
- transformBackwardTag: may never needed, don't see a use case here. But you'll never know.

> Users won't use the transform only with keys but also with keys/values, they expect similar workflow for both cases.

Yes, and I try to keep it so. But you insisted to use lazy transformation, which leads to different implementation.

**Comment by devemux86** [comment]
> So why you complain now and didn't made the proposal after I mentioned [this](https://dict.leo.org/german-english/retransform). That's time consuming for me, too.

No comments.

> We have four cases:

That should be discussed before all work to not waste time from anyone.

**Comment by Gustl22** [comment]
I don't know, but I don't see any sympathy for my problem. You ain't give a good reason why current transform state is the right approach? I don't believe you don't understand my hidden agendas(?)
Or what results do you expect from the discussions? :pensive:

**Comment by devemux86** [comment]
> Or what results do you expect from the discussions?

Seems that some expect from open source project administrators to merge anything without discussion and thorough testing.
In other repositories the pull requests are discussed for weeks before merging and pass a large series of changes.

**Comment by devemux86** [comment]
> We have four cases:

Why the 2 cases cannot be used in existing 2 rules if reverse the values inside the rules, that cannot work?

**Comment by Gustl22** [comment]
> In other repositories the pull requests are discussed for weeks before merging and pass a large series of changes.

Alright. This is my first and only major open source project. Library and you taught me a lot of things and I never experienced such a harsh discussion. So don't get me wrong if I ask these questions.

**Comment by Gustl22** [comment]
> Why the 2 cases cannot be used in existing 2 rules if reverse the values inside the rules, that cannot work?

You mean instead of reverse the `transformKey` map, we should reverse / swap `transformTag` map ?

**Comment by devemux86** [comment]
> This is my first and only major open source project.

And you're doing a fine job, please continue!

> So don't get me wrong if I ask these questions.

Really no problem at all. :slightly_smiling_face: 

I try to avoid situations - already met in other projects - where the merging run leaded to unstable releases. I try hard all these years to keep Mapsforge + VTM in good condition, that's why I prefer to be more strict than nice.

**Comment by devemux86** [comment]
> You mean instead of reverse the `transformKey` map, we should reverse / swap `transformTag` map ?

No, I meant instead of reverse any `Map` in code, to write the rules at theme in reverse order.
e.g. instead of write:
```xml
<tag-transform k="layer" v="building" k-match="building" v-match="yes" />
```
to write in reverse order if want for colors or anywhere something reverse:
```xml
<tag-transform k="building" v="yes" k-match="layer" v-match="building" />
```

**Comment by Gustl22** [comment]
> I try hard all these years to keep Mapsforge + VTM in good condition

Fully understandable. Thanks.

**Comment by Gustl22** [comment]
> to write the rules at theme in reverse order

How should a user expect this behaviour? Use forward direction for keys and backwards direction for tags with values in themes?

**Comment by devemux86** [comment]
Thing is that normally uses shouldn't care about 2 directions, just one-direction transform from input to output. That's why I don't like much so many variants and want to disconnect transform rules from the theme terms.

**Comment by Gustl22** [comment]
> Thing is that normally users shouldn't care about 2 directions, just one-direction transform from input to output.

Yes of course. That's why I use reversed map internally for several use cases. So user only defines "forward" transform. And internally I reverse it for the needs of library.

**Comment by Gustl22** [comment]
Example:
```
    <tag-transform k="kind" v="building" k-output="building" v-output="yes" />
    <tag-transform k="roof_color" k-output="roof:colour" />
    <tag-transform k="roof_direction" k-output="roof:direction" />
    <tag-transform k="roof_direction" v="e" k-output="roof:direction" v-output="90" />
    <tag-transform k="roof_direction" v="east" k-output="roof:direction" v-output="90" />
```

So internally I fetch the `roof_direction` from `roof:direction` tag with `transformBackward`. And then I look if element contains `roof_direction`. If tag is equal to (`roof_direction`,`e`) I can convert it to (`roof:direction`,`90`) with `transformForward`.

**Comment by devemux86** [comment]
> So internally I fetch the `roof_direction` from `roof:direction` tag with `transformBackward`. And then I look if element contains `roof_direction`. If tag is equal to (`roof_direction`,`e`) I can convert it to (`roof:direction`,`90`) with `transformForward`.

Thanks for the explanation. Can you add also the 2 other methods to see the complete picture?
And methods could be better named `transformBackwardX`, `transformForwardX`.
Also the `-output` rule suffix seems strange without `-input` pair. Can rename it to `-internal`, though don't like much the long tag names (but `ki` / `vi` would be confusing?).

**Comment by devemux86** [comment]
Also need more documentation in `IRenderTheme` to clarify what is considered forward and backward, to not search it in the future (e.g. your above [post](https://github.com/mapsforge/vtm/pull/678#issuecomment-468228630) describes the cases nicely).

**Comment by Gustl22** [comment]
> but `ki` / `vi` would be confusing?

I don't like long names either, but its better, otherwise _i_ can mean a lot (_int, in, input_).

**Comment by devemux86** [comment]
It still seems long, probably `-vtm` suffix could work better. Or another such small term...

**Comment by Gustl22** [comment]
Hmm can use `-vtm`, `-lib` or may `-itn`
`-vtm` is good, but would demarcate from mapsforge themes.

**Comment by devemux86** [comment]
> `-lib`

Even better, let's use that.

> `-vtm` is good, but would demarcate from mapsforge themes.

Mapsforge can be used (somehow) in VTM, but VTM themes cannot be used in Mapsforge.

**Comment by devemux86** [comment]
Thanks for the work, merged via 207993a6e23cc581320d244f52acbef7ff8fa95b.

**Pull request closed without merging**
