### PR TITLE
Add OSM and S3DB tags

### PR DESCRIPTION
**Pull request by Gustl22**
I did some code improvements in building layer and similar classes:
- add tag constants and some other constants
- add copyright (to keep clarity)
- add S3DB signature comment

In next step I add a PR which handles mapsforge/mapsforge#1014

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!
Squashed and merged via 149353119bb598af007ea8597ef04449b5ed5e79 (fixing some copyrights as there only author was @hjanetzek).

**Comment by andreynovikov** [comment]
As I see you are working hard on 3D buildings. As I understand you use building relations to get building outlines. But my experience is that considerable number of 3D buildings are not marked with relations. In this case you have to check if geometries are overlapping. Do you do that?

Also, have you succeeded with generation of extrusion meshes on server?

**Comment by devemux86** [comment]
> Also, have you succeeded with generation of extrusion meshes on server?

Focus by @Gustl22 seems being Mapsforge map files (writer + reader)?
(see also forum [announcement](https://groups.google.com/forum/#!topic/mapsforge-dev/aoYx6DZMiG8) for new Mapsforge maps version 5)

**Comment by Gustl22** [comment]
> But my experience is that considerable number of 3D buildings are not marked with relations. In this case you have to check if geometries are overlapping. Do you do that?

Yes, like I mentioned in PR mapsforge/mapsforge#1014, i calculate "implicit relations", which aren't tagged by OSM, but based on the geo-position. This may can be extended. I don't use relations from OSM for now, because the geo-inheritance must be calculated anyway.

> Focus by @Gustl22 seems being Mapsforge map files (writer + reader)?

Exactly :) 
Maybe can use Mapzen tiles, and I try to **efficiently** calc meshes from tags client-side (was not successfully yet). But sooner or later I have to implement an algo for mesh calculation.

**Comment by andreynovikov** [comment]
So, you want to do it on client side, not server side? Will it be public domain?

**Comment by Gustl22** [comment]
If I accomplish that client side, I would propose a new _unstable_ Layer. But have to work on that. Maybe can discuss this in forum, when I'm ready. Like Emux said, need to be real time :)

**Comment by devemux86** [comment]
A new layer seems a nice idea, as option to let user select which implementation wants.

**Pull request closed without merging**
