### PR TITLE
add MarkerRendererFactory interface and constructor 

### PR DESCRIPTION
**Pull request by stleusc**
to allow custom MarkerRenderer (extending default class) for specialized rendering needs

### CODE REVIEW

**Comment by devemux86** [comment]
Simpler why not adding an extra `MarkerLayer` constructor with a `MarkerRenderer` parameter?

Also let's keep each PR isolated with a feature / fix, i.e. `RenderBucket` API enhancement could be separate.

**Comment by stleusc** [comment]
Because this is the currently used constructor ```java new MarkerRenderer((MarkerLayer<MarkerItem>) this, defaultSymbol);``` where ```java this``` is ```java MarkerLayer```.

Does not really work then since to create one you need the other!

**Comment by stleusc** [comment]
Yes, I COULD have separated it but did not on purpose! Both changes, while different files, are one logical change to implement one feature. I see no purpose for one without the other. So I thought it makes sense to group it.

**Comment by devemux86** [comment]
Thanks!
Squashed and merged via 1fa9f133bd9a7332fb9146672aeabad2d95372d2 with fix of the unchecked cast.

**Pull request closed without merging**
