### PR TITLE
Rework Texture packer

### PR DESCRIPTION
**Pull request by Longri**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

From some quick tests, in densely populated areas e.g. Bilbao keep seeing OOM:
```java
org.oscim.android.test E/org.oscim.renderer.GLUtils: finish: glError 1285
```

**Comment by Longri** [comment]
Then there is another fundamental problem on this device.
The TextureAtlas can't get any smaller. 
I only have a picture of a TextureAtlas as I use it, because I still have a storage option built in.
But you can see that the algorithm is very effective after all.

internaldefault_ui_tmp_0

**Comment by devemux86** [comment]
Side note:
PR contains GPL code, that's unacceptable to library LGPL license.

**Comment by Longri** [comment]
What are you trying to tell me?
That you do not want commit the improvement and additionally want to abolish the TextureAtlas completely?

**Comment by devemux86** [comment]
- We cannot and will never include any GPL code or dependency in a non GPL project, like VTM which is LGPL.

- Each core change should justify its purpose, i.e. improve a situation, here there is no clear fix to the related issue.

- Texture atlas exists in VTM and remains for those want to use it. Naturally cannot be default since breaks library on low end devices.

**Comment by Longri** [comment]
:disappointed:

**Comment by devemux86** [comment]
In any case the PR contains changes which could be useful if were posted separately.

e.g. if have found an easier way to build native libs, I'll be happy to review it, but first and in a separate pull request.

Now there is a large amount of changes - not all related - which will require much of my free time to study them properly and ensuring VTM quality.

So I propose to progress in steps if want, one small change at a time, one small pull request at a time.
As a final step, the new native lib can be merged in its own feature branch, for thorough testing by all.

WDYT :slightly_smiling_face:

**Comment by Longri** [comment]
- Enable and fix JNI module #543

**Pull request closed without merging**
