### PR TITLE
vtm-android-example: permission for external storage - Android API 23

### PR DESCRIPTION
**Pull request by Gustl22**

### CODE REVIEW

**Comment by devemux86** [comment]
Also should implement then all permission workflow, if user selects "Don't ask again", all possible cases.
The whole thing becomes too complicated to maintain for simple API samples.

**Comment by devemux86** [comment]
_BTW why you appear as "First-time contributor", something wrong with your GitHub / Git credentials?_

**Comment by Gustl22** [comment]
I agree, it is not a compulsory part of vtm.. 
I recently had the issue, that I had to give the permissions on every new build while developing. And that's kind of exhausting. Especially for beginners, which may not instantly know how to access their files.

**Comment by Gustl22** [comment]
> _BTW why you appear as "First-time contributor"_

I re-logged-in yesterday in Android studio. But that shouldn't cause this message.. Did you already notice such a behaviour?

**Comment by devemux86** [comment]
> I re-logged-in yesterday in Android studio. But that shouldn't cause this message.. Did you already notice such a behaviour?

Actually it's been a very long time with that tag, just forgot to mention it.

**Comment by devemux86** [comment]
Samples seem working in their current implementation for now with a simple way.

> Especially for beginners, which may not instantly know how to access their files.

Users should study Android documentation for permissions, location providers, etc.
All these can be done also with third-party libraries, so we shouldn't mix with those.

**Comment by Gustl22** [comment]
Ok, it was worth a try ;D

**Comment by Gustl22** [comment]
> Actually it's been a very long time with that tag, just forgot to mention it.

Didn't found a setting for this (?). Cannot explain me that...

**Comment by devemux86** [comment]
Also for future reference, if things become mandatory from Android: :slightly_smiling_face: 

Permissions process should be done in app level (e.g. all Mapsforge activities), not in lib level (i.e. file picker).

**Comment by devemux86** [comment]
> Didn't found a setting for this (?). Cannot explain me that...

_Have you changed your registered email in GitHub profile?
Do you use a different email in Git commits compared to GitHub?
Some kind of identification difference could be the cause._

**Comment by Gustl22** [comment]
> Permissions process should be done in app level (e.g. all Mapsforge activities), not in lib level (i.e. file picker).
:+1: yes that's cleaner, but would be even worse to maintain :D

**Comment by Gustl22** [comment]
Test from Fasthub

**Comment by Gustl22** [comment]
_Weird, I have access to Github via Fasthub even after clearing session (via another device) and changing PW. Sorry this may not belongs here. I checked the email, too and it's everywhere the same. Never changed it also._

**Pull request closed without merging**
