### PR TITLE
fix TileCache, cacheDirectory was ignored

### PR DESCRIPTION
**Pull request by stleusc**

### CODE REVIEW

**Comment by stleusc** [comment]
I ran gradlew clean build on my second commit and it passes.
Any idea why it failed here?

**Comment by stleusc** [comment]
This is the error:

> X.5 CertificateFactory not available: try using a newer JVM to build your application.

???

**Comment by devemux86** [comment]
About Travis it's the usual random errors.

**Comment by devemux86** [comment]
Existing samples fail to work with the PR changes.

**Comment by devemux86** [comment]
Squashed and merged via 85adc04a05bfa3a2cfe5b5b0101e75d1f88f1435.

I also pushed additional improvements and fixed the Samples.

**Comment by devemux86** [comment]
BTW you can add your name in modified files header, see existing.

**Comment by andreynovikov** [comment]
Hm. I just wanted to push my own fix to that. Good I've looked here before. The problem with this commit is that directory can be null and this is ok. My version considers this.

**Comment by devemux86** [comment]
I pushed on top a fix for that so the Samples (which have `null`) to work again.
Can you confirm it is ok?

**Comment by stleusc** [comment]
Yes, this is fine...
My use case was to supply directory ;-)
Thanks!

**Pull request closed without merging**
