### PR TITLE
* change both MarkerLayer example, Desktop and Android, to use TextureRegions instead of Bitmaps. With creation of TextureAtlas at runtime

### PR DESCRIPTION
**Pull request by Longri**
* change both MarkerLayer example, Desktop and Android, to use TextureRegions instead of Bitmaps. With creation of TextureAtlas at runtime
* fix dependency of android-example to vtm project
* add platform identification

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!
Merged via 120182ec15ade8083c023923fb38fdc0f13568a5 with new examples.

**Comment by Longri** [comment]
> We don't need (?) an explicit platform declaration

I guess so!
So the user has to decide if he sets the flag (GLAdapter.GDX_DESKTOP_QUIRKS = true) on the desktop.
Or under iOS he must set PolygonBucket.enableTexture to false and with createTextureRegions he must flip the Y-Axis! 

Maybe I have forgot another point or we have some situations in the future?

**Comment by devemux86** [comment]
In `GLAdapter` we have:
- OpenGL quirks for desktop and web
- Android Adreno GPU workaround
- Circles rendering via quads or points

Also macOS needs `BuildingLayer.TRANSLUCENT = false;` (see #61).

Regarding initialization, `GLAdapter.GDX_DESKTOP_QUIRKS = true;` is set in `GdxMapApp.init`.
So you could add also `PolygonBucket.enableTexture = false;` in `IOSMapApp.init` too?

**Comment by Longri** [comment]
Another situation!
If you have the same core code for the initialization of the MarkerLayer and do not do this in the corresponding starter projects, how do you decide if the Y axis needs to be flipped?

I think the user needs to consider a lot of things that we need to document.

It would be nice if we could take it off here!

**Comment by Longri** [comment]
> Also macOS needs BuildingLayer.TRANSLUCENT = false; (see #61).

Maybe we can extend the Platform Enum with MAC_OS but we musst decide this and I do not know how

**Comment by devemux86** [comment]
>If you have the same core code for the initialization of the MarkerLayer and do not do this in the corresponding launcher projects, how do you decide if the Y axis needs to be flipped?

So far cases like the GL quirks are handled in VTM core, that's why we needed explicit flags.
Overlays are supposed to be initialized in clients, which know on what platform they are.

But you have right, eventually a central way could help.
I opened #285, need to think a bit the implementation and check what it affects.

**Comment by Longri** [comment]
> Overlays are supposed to be initialized in clients, which know on what platform they are.

For me not, all layers are initialized in the core project.
This does not have any dependencies on any platform!

https://github.com/Longri/cachebox3.0/blob/master/core/src/de/longri/cachebox3/gui/map/layer/WaypointLayer.java

**Comment by devemux86** [comment]
Ok I understand.
Could you create a separate PR with the `Platform` enum for start and I'll see next how we can handle other core flags?
(please merge latest master first :slightly_smiling_face:)

**Comment by Longri** [comment]
👍 I will do that on this weekend

**Comment by Longri** [comment]
or earlier!

**Pull request closed without merging**
