### PR TITLE
vtm-models: add 3D models, rename treeA.g3dj

### PR DESCRIPTION
**Pull request by Gustl22**
Add this models:
3d_models

and make "treeA" metric (right scale implementation follows in separate PR).

Do not wonder: models won't work with current `GdxRenderer3D`.

### CODE REVIEW

**Comment by devemux86** [comment]
As a separate PR perhaps the `A` could be removed from `treeA` name and its code and keep the `tree` naming?

**Comment by Gustl22** [comment]
Like that?

**Comment by devemux86** [comment]
Indeed is more clean code now.

**Comment by devemux86** [comment]
Merged in branch [issue_582](https://github.com/mapsforge/vtm/tree/issue_582).

> and make "treeA" metric (right scale implementation follows in separate PR).

Indeed their scale now is not normal. Perhaps their model change should be with the other changes.

**Comment by devemux86** [comment]
Thanks!
Merged via d36320967c87189b20e4210bf7b221de38481f67 without the tree scaling.

**Pull request closed without merging**
