### PR TITLE
Real time (SVG) texture atlas

### LINKED ISSUE #63: Real time (SVG) texture atlas
Generate an SVG texture atlas from `.svg` symbols (at runtime?) depending on device dpi.

The need is for increase OpenGL performance on SVG texture rendering.

### PR DESCRIPTION
**Pull request by Longri**
Will close #63 !
With example for Android and desktop!

### CODE REVIEW

**Comment by Longri** [comment]
wy is travis failed?

**Comment by devemux86** [comment]
See Travis [log](https://travis-ci.org/mapsforge/vtm/builds/208128909#L1463), you can write it as:
```java
SymbolStyle.SymbolBuilder<?> symbolBuilder = new SymbolStyle.SymbolBuilder();
```

**Comment by devemux86** [comment]
Nice!
Merged via 2d3ab0b6fd0ea9c5243ce8fd5268066501d073d6 with improvements via 808671c1fbe3cb06b30f0c7bca6a1a9ed8a62cb7.

**Comment by devemux86** [comment]
I improved the implementation particularly in `XmlAtlasThemeBuilder` and simplified the samples.
@Longri please check if all working as intended.

**Pull request closed without merging**
