### PR TITLE
some code improvements

### PR DESCRIPTION
**Pull request by lucaosten**
- reduced memory usage of RenderBucket by making "type" byte instead of int
- improved code readability by renaming variable
- added latitude/longitude validation methods to GeoPoint
- solved Java double precision problem in GeoPoint
- made GeoPoint Serializable for easier Android usage
- made BoundingBox.toString() human readable for better debugging

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

Regarding pull requests, it could be more convenient to use a [topic branch](https://help.github.com/articles/about-pull-requests/) for each PR, maintaining your master synhcronized to upstream.

Unfortunately your pulls requests seem rejected from Travis as "Abuse detected" (seen [here](https://travis-ci.org/mapsforge/vtm/requests)).
Contacting Travis support I got the following answer:

_"We are blocking that request because calimoto-GmbH is an unknown organization to Travis. While this is intended to stop abuse, it does unfortunately cause some issues in situations like these where one user or organization is not using Travis. We are looking into fixing this, as we don't feel that an organization as a whole should have to create a Travis account when working with another that is using Travis CI.
For the time being, a work around would be to have someone in the calimoto-GmbH organization to be enable Travis for the organization and push a new commit to the PR or close and reopen the PR."_

I hope that can be solved as Travis pull request builds are very helpful.
Or else even simple PRs would need verification and merge via command line.

**Comment by lucaosten** [comment]
We are currently not using Travis and therefore it does not make sense for use to make a plan with them only to allow pull requests.
Therefore verification and merge via command line would be the only possibility at this point. Is this something we have to do?

**Comment by lucaosten** [comment]
Would alternatively a repository from my private account solve this problem?

**Comment by devemux86** [comment]
> Would alternatively a repository from my private account solve this problem?

That should work, as all other pull requests are coming from users and work ok.
I'll ask again Travis support if there is something else they can do.

**Comment by devemux86** [comment]
@lucaosten Travis suggestion follow, seems the organization is empty from people posting the PR from its repositories.

_"Would it be possible that just some user belonging to the organization calimoto-GmbH lcould login into Travis once? They don't need to make any plans at Travis, we just need their Github login and then everything would work.
Looking at the PR, the user lucaosten is already in our Database so when he tries to send a PR it would work."_

**Comment by devemux86** [comment]
Thanks!
Squashed and merged via 490b932eabce182cd81e2523cde945c34965767c.
- Moved the latitude / longitude validation methods in `GeoPointUtils` (like Mapsforge `LatLongUtils`)
- Fixed some copyrights, not needed in refactored classes, only in actual changes

> Would alternatively a repository from my private account solve this problem?

@lucaosten since it doesn't seem a solution, please post next pull requests from an account where the Travis builds can work. :slightly_smiling_face:

**Pull request closed without merging**
