### PR TITLE
Implement Bitmap.getPngEncodedData()

### PR DESCRIPTION
**Pull request by Longri**
Please merge. I need this for my project

### CODE REVIEW

**Comment by devemux86** [comment]
>I need this for my project

In which platform?

**Comment by Longri** [comment]
for all platforms! iOS, Android and Desktop!

**Comment by devemux86** [comment]
As mentioned in the forum, `vtm` module would better remain free of dependencies.

We already have a `vtm-gdx` module, so will need to think a way to satisfy that request.

**Comment by Longri** [comment]
ok! I have a solution! 

Send new commit in a few minutes!

**Comment by devemux86** [comment]
Also not forcing `vtm-android` having libGDX as dependency.
That part belongs to `vtm-android-gdx`.

**Comment by Longri** [comment]
I think this is a good compromise!

**Comment by devemux86** [comment]
Yes that's much better (and generic).
Give me some time to review it.

**Comment by devemux86** [comment]
Squashed and merged via 44b40608f6bbfb27193c2e58b1a6d7cb276c12aa.
I pushed some improvements, see if all are ok.

**Pull request closed without merging**
