### PR TITLE
Set screen offset for bitmap rendering

### PR DESCRIPTION
**Pull request by andreynovikov**
Adds ability to offset bitmap overlay (no need to use transparent margins).

P.S. I do not understand the meaning of `scale` so I have copied it as-is.

### CODE REVIEW

**Comment by devemux86** [comment]
Can you explain what's the use case of this?
You want to offset the marker overlay bitmap position?

**Comment by devemux86** [comment]
I see the only use of the `BitmapRenderer` is in unused `BitmapLayer` and `MapScaleBar`.

What's your use case?

**Comment by andreynovikov** [comment]
I use it in my MapScaleBar. I have rewritten it to be DPI friendly and by this code I place it where I want on a map. Can push modified MapScaleBar later.

**Comment by devemux86** [comment]
About the scale bar see my remarks on #84.
I have a ready implementation with a far more versatile positioning, will try to merge later.

Until then we can postpone the PR?

**Comment by devemux86** [comment]
>Can push modified MapScaleBar later.

Unless you have an implementation that works on all platforms? :smile:

**Comment by andreynovikov** [comment]
I think this PR is generic enough to be accepted. Unless you plan to remove BitmapLayer completely.

**Comment by devemux86** [comment]
>Unless you plan to remove BitmapLayer completely.

No, I don't intend to deprecate any API.

**Comment by devemux86** [comment]
@andreynovikov see a more versatile implementation in #87.

**Comment by andreynovikov** [comment]
Cool!

**Pull request merged**
