### PR TITLE
ColorUtil: fix modHSV, Color: HSV

### PR DESCRIPTION
**Pull request by Gustl22**
Sorry I have some changes for the building colors. After this a PR follows to customize HSV in render themes.

### CODE REVIEW

**Comment by devemux86** [comment]
Travis complains for failing tests?

> After this a PR follows to customize HSV in render themes.

Do you mean [ThemeStylerActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/ThemeStylerActivity.java) sample?

**Comment by devemux86** [comment]
Did you change the existing HSV limits?

**Comment by Gustl22** [comment]
> Do you mean ThemeStylerActivity sample?

Thanks for the hint. No I meant for extrusions, cause their colors are predefined by tile source and not changeable in themes. Refering this [TODO](https://github.com/mapsforge/vtm/blob/b9c7d4cbb1df6eb8e03353b27c0a2ad5fd84560d/vtm/src/org/oscim/layers/tile/buildings/S3DBUtils.java#L45) by Janetzek.

> Please explain in detail the `modHsv` changes for each variable.

- hue: changed from multiplying hue to add / shift hue. [Hue](https://en.wikipedia.org/wiki/HSL_and_HSV) is the circular value and needs a shift to be changed. Example: if having color red(255, 0, 0) the hue is `hue = 0`. If want to change the hue you never can do it because `0 * x = 0`. So the hue will remain, although its a color. Multiplying makes no sense here.
- saturation: now same principle like `value`: 
    - `relative = false` changing to 2 is fully saturated. 
    - `relative = true` changing to 2 is twice saturated as before. Means colors with nearly no saturation cannot be saturated (like it is in current master).
- value: no change of results, but simplified checks.

**Comment by Gustl22** [comment]
Finally got it working... What a mess :)

**Comment by devemux86** [comment]
Thanks, merged via 627a316e4dd34960bc6aa3d15cdd6f5d4e58b705.

**Pull request closed without merging**
