### PR TITLE
Updated vtm-web and vtm-web-app to work with libgdx1.9.4 and GWT2.7.0

### PR DESCRIPTION
**Pull request by schedul-xor**

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks!

Why the need of sound manager?

**Comment by schedul-xor** [comment]
You're right. Sound manager is completely unnecessary. Actually, I now realized the reason why GwtApplication was overwritten.

**Comment by devemux86** [comment]
Hmm now I don't see a map?

Some additional notes:
- Isn't GWT latest version `2.8.0`?
- Are there any plans for the `vtm-web-js` module?
- There is work (in TODO items) for various graphics operations, e.g. to enable symbols.
- Also could you remove the `UrlTileSource` since it's unrelated to the PR and should be handled separately (probably with a `StringBuilder`)?

**Comment by schedul-xor** [comment]
It seems that I've over-deleted while deleting sound manager...

By the way,

> Isn't GWT latest version `2.8.0`?

Yes, the latest GWT is v2.8.0. But the latest libGDX v1.9.4 is based on GWT v2.6.0, and ru.finam:slf4j-gwt v1.7.7.1 (updated in commit 877d217) is based on GWT v2.7.0. I tried GWT v2.7.0, and it just worked.

> Are there any plans for the vtm-web-js module?

Not yet. Currently vtm-web-js succeeds building, but fails while launching. I need time to dig in the code.

> There is work (in TODO items) for various graphics operations, e.g. to enable symbols.

Yes, you're right. Current implementation removes the loaded image element from DOM after uploading the bitmap texture to buffer, and probably that's the reason why it's not working.

> Also could you remove the UrlTileSource since it's unrelated to the PR and should be handled separately (probably with a StringBuilder)?

OK, I will separate the URL string building work from this PR (I will make a new PR). Would you please merge it as soon as possible? `String.format()` cannot be used in GWT, so the build won't succeed unless it's replaced to something else.

**Comment by devemux86** [comment]
>Current implementation removes the loaded image element from DOM after uploading the bitmap texture to buffer, and probably that's the reason why it's not working.

Now the the themes use SVG resources, something to check for web too.
Also I had added several new methods in graphics interfaces, which would need implementation for web too (they have TODO items).

**Comment by devemux86** [comment]
Thanks for the PR!
Rebased, squashed and merged via 308497ffa60fafa087d195bbe7deb60a7f88ecb6.

**Pull request closed without merging**
